openhwgroup/cv32e40x

.github/ISSUE_TEMPLATE/config.yml
README.md

Fixing reference to cv32e40p

---

cv32e40x_manifest.flist

Added missing file to manifest.

---

rtl/cv32e40x_core.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv

Fixed pin lists in instantiations

---

docs/user_manual/source/control_status_registers.rst

Fixed tdata2 mode

---

rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv

Further fix for https://github.com/openhwgroup/cv32e40x/issues/20 (needed because of unfortunate merge)

Make instances match

---

bhv/cv32e40x_wrapper.sv

Tied of unused signals in wrapper

---

rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/include/cv32e40x_pkg.sv

They remain unused for now, but will be used when the controller is rewritten.

Added propagation of exception related signals to WB stage.

---

rtl/cv32e40x_core.sv
rtl/cv32e40x_data_obi_interface.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_instr_obi_interface.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/include/cv32e40x_pkg.sv

PMA is instantiated, but controller is not updated yet.
SEC clean vs 39aeb6c

Instantiate PMA on data bus

---

bhv/cv32e40x_wrapper.sv
sva/cv32e40x_mpu_sva.sv

Update MPU assertions. Bind MPU assertions to MPU in LSU

---

rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv

SEC equivalent with 63cc68c991e3bb99f55468fc9a8ab3e61c9f5381

Moved register file from ID stage to toplevel.

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/cv32e40x_pma.sv
sva/cv32e40x_mpu_sva.sv

This works around issue reported in https://github.com/openhwgroup/cv32e40x/issues/39

Fix range of PMA_CFG parameter to avoid negative indexes

---

rtl/cv32e40x_if_stage.sv

Fixed minor assignment issue in if_stage

Fixed compressed instruction assigment in if_stage

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_wb_stage.sv
sva/cv32e40x_cs_registers_sva.sv

Remove logic from top level

---

rtl/cv32e40x_cs_registers.sv

Fix reference to undecleared signal

---

bhv/cv32e40x_tracer.sv
bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_alignment_buffer.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_prefetch_unit.sv
sva/cv32e40x_alignment_buffer_sva.sv
sva/cv32e40x_core_sva.sv

Cleanups to semantics of pipeline valid/ready and addition of kill_if as precursor to the new controller.
All SEC equivalent with f85707ecea27d14e4d89a97122fdd454463580d2

Updates to pipeline valid/ready and kill_if

---

docs/user_manual/source/pma.rst
rtl/cv32e40x_core.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/cv32e40x_pma.sv
rtl/include/cv32e40x_pkg.sv

Updates in response to https://github.com/openhwgroup/cv32e40x/issues/36

PMA updates

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_ff_one.sv

Lint clean up

---

docs/user_manual/source/pma.rst
rtl/include/cv32e40x_pkg.sv

Update default attribution when PMA is deconfigured

---

docs/user_manual/source/pma.rst

Doc update to address issue #68

---

cv32e40x_manifest.flist
rtl/cv32e40x_alu.sv
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/include/cv32e40x_pkg.sv

Add B decoder and simple imlementation of Zba

---

rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/include/cv32e40x_pkg.sv

Use uppercase in enum used for parameter

---

bhv/cv32e40x_rvfi.sv

Fixed RVFI issue where mstatus update could be attributed to the wrong cycle for interrupts.

Fixed RVFI mstatus issue

---

docs/user_manual/source/integration.rst
docs/user_manual/source/intro.rst

Updated versions for B and Zce support

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_a_decoder.sv
rtl/cv32e40x_alu.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_data_obi_interface.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_m_decoder.sv
rtl/cv32e40x_mult.sv
rtl/cv32e40x_wb_stage.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_id_stage_sva.sv
sva/cv32e40x_mult_sva.sv

First step in LSU and signal name clean up; SEC clean

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_div.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_wb_stage.sv
sva/cv32e40x_core_sva.sv

Further clean up of ready/valid signals

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv

Update modelling related to new meaning of valid signal in RTL,
Fixed issue related to modelling pc_wdata when killing if, fixed issue with debug.

Rvfi fixes

---

rtl/cv32e40x_cs_registers.sv

Also removed zero-suppression of csr_waddr as these come from dedicated flops.
SEC clean.

Reverted removal of zero-suppresion of csr_raddr

---

rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_id_stage.sv

Ready/valid cleanup; SEC clean

---

sva/cv32e40x_core_sva.sv

Updated wrt to updated id_valid definition; sva only; SEC clean

---

bhv/cv32e40x_rvfi.sv

Removed handling of mstatus in RVFI left over from old controller.

Removed handling of mstatus in RVFI left over from old controller

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_id_stage_sva.sv

Undid some valid/ready handshakes to regain area; fixed some todos

---

reference/readme.txt
reference/rvb_bextdep.v
reference/rvb_bitcnt.v
reference/rvb_bmatxor.v
reference/rvb_clmul.v
reference/rvb_crc.v
reference/rvb_full.v
reference/rvb_shifter.v
reference/rvb_simple.v
reference/rvb_zbb32.v

Added bit manipulation reference code (approved for addition in CQ 23398)

Added bit manipulation reference code from https://github.com/riscv/riscv-bitmanip.git; approved in CQ 23398

---

rtl/cv32e40x_ex_stage.sv

SEC must be checked, currently there is a very long runtime

Factoring halt_ex into EX stage local instr_valid.

---

rtl/cv32e40x_load_store_unit.sv

Load store unit could incorrectly signal valid_1_o when the first part of a misaligned load/store was in WB.
Added a 'last_q' bit which is set to 1'b1 when the last part of a misaligned load/store goes from EX to WB.

Added 'last' signal in lsu to check for last part of misaligned transfers

---

rtl/cv32e40x_alu.sv

Integrated rvb shifter. 
SEC Clean.
~200 gate area increase in ALU, but ~400 gate decrease on top level. Half of the reduction happens in if_stage_i.instruction_obi_i, the rest is spread out.

Initial integration of the rvb shifter

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_alu_b_cpop.sv
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/include/cv32e40x_pkg.sv

Implemented Zbb and Zbs instructions
Changes are SEC clean with the top level parameter  B_EXT == NONE.

Implemented B extensions Zbb and Zbs

---

docs/user_manual/source/intro.rst
docs/user_manual/source/x_ext.rst

Initial documentation for eXtension interface

---

docs/user_manual/source/x_ext.rst

Extension interface related updates: Clarified stability requirements separated memory response from memory result

---

rtl/include/cv32e40x_pkg.sv

Update MARCHID to 20

---

docs/user_manual/source/control_status_registers.rst
docs/user_manual/source/integration.rst

User Manual only. eXtension interface parameter additions

---

sva/cv32e40x_mpu_sva.sv

Assertion fixes

---

rtl/cv32e40x_controller_fsm.sv

Used ebreakm as condition to allow debug entry from ebreak

---

sva/cv32e40x_mpu_sva.sv

Reverts openhwgroup/cv32e40x#144

Revert "Assertion fixes"

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_m_decoder.sv
rtl/include/cv32e40x_pkg.sv

SEC clean with B extension enabled
SEC clean with B extension disabled

ALU area optimizations

---

docs/user_manual/source/intro.rst

Documentation only: OBI link fix

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_controller_fsm.sv

Reviewed rvfi code and added todos

---

docs/user_manual/source/x_ext.rst

Documentation only: eXtension interface updates

---

docs/user_manual/source/x_ext.rst

Documentation only: eXtension interface: added privilege mode info

---

reference/el2_exu_mul_ctl.sv
reference/el2_ifu.sv
reference/el2_ifu_bp_ctl.sv
reference/readme.txt

Bit Manipulation code from SweRV (approved for inclusion in CQ 23537)
Branch prediction code from SweRV (approved for inclusion in CQ 23538)

Branch prediction and bit maipulation code from SweRV

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_b_decoder.sv
rtl/include/cv32e40x_pkg.sv

Implemented  the Zbc B extension.
Sequentially equivalent for B_EXT=NONE and B_EXT=ZBA_ZBB_ZBS. Enabled with B_EXT=ZBA_ZBB_ZBC_ZBS.

Implemented the Zbc B extension

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv

Made B_EXT a top level parameter

---

docs/user_manual/source/intro.rst

Documentation only. Synthesis related updates

---

rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_mpu_sva.sv

Update the MPU and it's assertions to be in sync with E40s.
Remove remnants of PMP

Mpu update pmp removal

---

reference/beh_lib.sv
reference/el2_exu.sv
reference/el2_exu_alu_ctl.sv
reference/el2_exu_div_ctl.sv
reference/readme.txt

Added SweRV reference code (CQ 23532)

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv

Added debug mode and debug cause signal, renamed rvfi_dbg signal to rvfi_debug to match spec.

RVFI debug updates

---

bhv/cv32e40x_rvfi_trace.svh
docs/user_manual/source/rvfi.rst

RVFI tracer: Added missing file name, updated docs

---

rtl/cv32e40x_ex_stage.sv

..after proving SEC for factoring halt_…ex into EX stage local instr_valid.

Removed commented line and todo 

---

rtl/cv32e40x_mpu.sv

Fix bug resulting in OBI req possibly being retracted before grant.
This also fixes possibe obi.gnt->obi.req timing dependency.

Fix bug resulting in OBI req possibly being retracted before grant.

---

docs/user_manual/source/rvfi.rst

Updated and fixed formatting in RVFI documentation

---

bhv/cv32e40x_rvfi.sv

Updated rvfi_trap and rvfi_intr behavior to match updated spec.

Rvfi trap intr update

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv

Fixed todos and updated comments. Moved register file data probes to register file wrapper boundry.

Rvfi todo cleanup

---

rtl/cv32e40x_controller_bypass.sv

We now have a single write port to the register file, and this hazard is obsolete.
NOT SEC clean.

Removed WAW stall.

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv

Fixed RVFI syntax causing issues for formal

---

docs/user_manual/source/control_status_registers.rst

Updated width of mcause exception codes.

---

rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv

SEC clean if data_err_i is assumed to be 1'b0;

Added support for NMI.

---

rtl/cv32e40x_register_file.sv

Updated Register file header and description, updated mem reset values to generic word width.

Minor cleanup in register file

---

rtl/cv32e40x_load_store_unit.sv

Bugfix: Non-naturally aligned halfwords would not be signalled as misaligned unless they needed to be split in two transactions.

Bugfix: Non-naturally aligned halfwords

---

docs/user_manual/source/fencei.rst

Corrected fencei description

---

bhv/cv32e40x_core_log.sv
sva/cv32e40x_div_sva.sv
sva/cv32e40x_mpu_sva.sv
sva/cv32e40x_mult_sva.sv

Cleanup of code triggering warnings in formal verif

---

sva/cv32e40x_alignment_buffer_sva.sv
sva/cv32e40x_mpu_sva.sv

Fixed erroneous assertion and cleaned up warnings

---

rtl/cv32e40x_controller_fsm.sv

Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

fix derivation of nmi_is_store_q to identify store or load NMI faults

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
bhv/include/cv32e40x_wrapper.vh

RVFI: Fixed lint warnings and fixed issue with pma register assignment

---

bhv/cv32e40x_rvfi.sv

Fixed RVFI issue where debug happens on second back-to-back interrupt and does not signal second interrupt.
Passes debug regressions and interrupt assertions.

Fixed RVFI issue

---

rtl/cv32e40x_alignment_buffer.sv
sva/cv32e40x_alignment_buffer_sva.sv

Timing ops for alignment buffer

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
docs/user_manual/source/exceptions_interrupts.rst
docs/user_manual/source/integration.rst
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_rvfi_sva.sv

Make irq_ack/id internal and add dbg_ack

Fix github issue #231

---

bhv/cv32e40x_wrapper.sv

Renamed xif signals in wrapper file

---

rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/include/cv32e40x_pkg.sv

Changed trigger match PC comparison to use IF stage PC instead of ID stage.
SEC clean

Trigger uses PC from IF stage

---

cv32e40x_manifest.flist
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_wb_stage.sv
rtl/if_xif.sv

Removed x_ prefixes and renamed interface file

---

docs/user_manual/source/exceptions_interrupts.rst

Added section about NMI to the user manual.

---

bhv/cv32e40x_wrapper.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_mpu_sva.sv
sva/cv32e40x_write_buffer_sva.sv

Updated pma-related assertions to account for unreachables and write buffer

Updated pma-related assertions

---

sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv

Updated assertions for debug single step + interrupt taken.

---

bhv/cv32e40x_wrapper.sv
sva/cv32e40x_core_sva.sv

Fixed wrong assertion and bind statement not supported in xcelium

---

bhv/cv32e40x_wrapper.sv
cv32e40x_manifest.flist
docs/user_manual/source/load_store_unit.rst
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_lsu_response_filter.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_load_store_unit_sva.sv
sva/cv32e40x_lsu_response_filter_sva.sv

Implemented response filter in the load/store unit for performance improvements to bufferable writes.

Implemented response filter in lsu

---

docs/user_manual/source/exceptions_interrupts.rst

Fixes the following:
https://github.com/openhwgroup/cv32e40x/issues/313
https://github.com/openhwgroup/cv32e40x/issues/315

Fix for #313 and #315

---

docs/user_manual/source/load_store_unit.rst
docs/user_manual/source/pma.rst
docs/user_manual/source/rvfi.rst

Updates related to #54 and #218

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
docs/user_manual/source/rvfi.rst
sva/cv32e40x_rvfi_sva.sv

Expand rvfi_trap to provide more information about trap type and cause

---

reference/readme.txt

Updated reference code status

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
docs/user_manual/source/rvfi.rst

Updated naming and added comments for readability, removed irrelevant column from rvfi_intr table.
Addresses issues pointed out in #299 and #300 

RVFI updates for readablility

---

docs/user_manual/source/conf.py
docs/user_manual/source/control_status_registers.rst
docs/user_manual/source/intro.rst
docs/user_manual/source/rvfi.rst

Introduced RISC-V names for counter extension

---

docs/user_manual/source/integration.rst

Changed minimum ID_WIDTH to 3

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_if_stage.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_id_stage_sva.sv

Combined pc mux and exception pc mux

---

docs/user_manual/source/intro.rst

Add Zkt and Zbkc in list of supported standard extensions

---

rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
sva/cv32e40x_controller_fsm_sva.sv

Added assertions to back up removal where needed.
SEC clean.

Fixed TODOs in the controller.

---

rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_int_controller.sv
rtl/include/cv32e40x_pkg.sv

Fix todo's

---

rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv

Rename register file related signals to get consistent naming

---

bhv/cv32e40x_wrapper.sv

Fix probing of deleted priv_lvl in cv32e40x_wrapper

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
docs/user_manual/source/rvfi.rst

Connected to flops in the controller.
Updated documentation for newly added rvfi_nmip.

Added rvfi_nmip.

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_wb_stage.sv
sva/cv32e40x_load_store_unit_sva.sv

Todo removals

---

rtl/cv32e40x_decoder.sv
rtl/cv32e40x_id_stage.sv

Clean up enable signals in ID-EX pipeline

---

rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_wb_stage.sv

Syntax only change

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
docs/user_manual/source/rvfi.rst
sva/cv32e40x_rvfi_sva.sv

Added bits [13:12] to rvfi_trap.

Added bits to rvfi_trap

---

rtl/cv32e40x_load_store_unit.sv

Removed local lsu_en_gated from the load_store_unit, as this is equivalent to valid_0_i computed in the EX stage.
Refactored LSU ready_1_0, done_0 and valid_0_o.
SEC clean.

Load store unit todo removal and refactor

---

rtl/cv32e40x_a_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv
sva/cv32e40x_ex_stage_sva.sv
sva/cv32e40x_id_stage_sva.sv

Bug fix for atomic operations (LSU will get out of sync with pipeline if both alu_en and lsu_en are 1).
Not SEC clean (SEC clean if A_EXT=0)

Fix for atomic operations

---

rtl/cv32e40x_a_decoder.sv

Fix LR decoding (rs2 field should be checked to be 0).
Not SEC clean (SEC clean if A_EXT=0)

Fixed atomic LR decoding

---

rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_m_decoder.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_id_stage_sva.sv

Preparation step for further clock gating of operands and sys_* bits

---

rtl/cv32e40x_id_stage.sv

Further clock gating

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv

Fixes according to renamed signals

---

rtl/cv32e40x_id_stage.sv

Clock gating optimization

---

rtl/cv32e40x_cs_registers.sv

Removed todo in cs_registers.

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_m_decoder.sv
rtl/include/cv32e40x_pkg.sv

Share operands between multiplier and divider

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_a_decoder.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/include/cv32e40x_pkg.sv

Preparing LSU for XIF

---

bhv/cv32e40x_wrapper.sv
docs/user_manual/source/integration.rst
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_m_decoder.sv
rtl/include/cv32e40x_pkg.sv

Add M_EXT parameter.
Update MISA to take M_EXT, X_EXT, X_MISA into account

Add M_EXT parameter

---

docs/user_manual/source/integration.rst

Added alignment restriction

---

docs/user_manual/source/fencei.rst
docs/user_manual/source/load_store_unit.rst
docs/user_manual/source/pma.rst

User manual updates related to PMA, fencei and write buffer

---

README.md
docs/user_manual/source/intro.rst

Updated Zc version

---

docs/user_manual/source/conf.py
docs/user_manual/source/index.rst
docs/user_manual/source/preface.rst

Changelog experiment (not functional yet)

---

docs/user_manual/requirements.txt

Added requirement

---

docs/user_manual/source/integration.rst
docs/user_manual/source/intro.rst

Added RV32 parameter

---

docs/user_manual/source/intro.rst
docs/user_manual/source/pipeline.rst

Text improvements as in https://github.com/openhwgroup/cv32e40p/pull/679

---

docs/user_manual/source/pipeline.rst

Updated cycle counts and hazards.

---

docs/user_manual/source/preface.rst

DOCS: Cleaned up changelog section in user manual

---

README.md
docs/user_manual/source/control_status_registers.rst
docs/user_manual/source/exceptions_interrupts.rst
docs/user_manual/source/integration.rst
docs/user_manual/source/intro.rst

CLIC related documentation updates

---

bhv/cv32e40x_wrapper.sv
docs/user_manual/source/exceptions_interrupts.rst
docs/user_manual/source/integration.rst
rtl/cv32e40x_core.sv

Updated CLIC interface signals and added them to documentation

---

docs/user_manual/source/integration.rst

Added missing signal in user manual integration guide

---

docs/user_manual/source/control_status_registers.rst

Fixed tinfo read values.
Typos fixes.

Doc only: Tinfo and typos

---

docs/user_manual/Makefile
docs/user_manual/source/conf.py

Added copyright headers (not an actual documentation update)

---

rtl/cv32e40x_core.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_sleep_unit.sv

Removed unused clock signal

---

rtl/cv32e40x_load_store_unit.sv

LEC clean
Slight area reduction

Simplified sign extension logic in LSU

---

rtl/if_xif.sv

Added monitor ports to xif

---

bhv/cv32e40x_wrapper.sv
bhv/rvfi_sim_trace.sv
cv32e40x_manifest.flist

Add tracer for waveform annotation with assembly instruction etc

---

rtl/cv32e40x_cs_registers.sv
rtl/include/cv32e40x_pkg.sv

Removed obsolete bitfields

---

bhv/rvfi_sim_trace.sv

Updated sim tracer to use explicit casting to avoid causing issues for some simulators.

Fixed dsim/vsim compatibility

---

docs/user_manual/source/integration.rst
docs/user_manual/source/preface.rst
docs/user_manual/source/rvfi.rst

Made rvfi_intr multibit. 
Fixed user manual compile issues

Made rvfi_intr multibit

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/include/cv32e40x_pkg.sv

RTL updates according to https://github.com/openhwgroup/cv32e40x/pull/460

Split mimpid into major, minor,patch

---

bhv/cv32e40x_rvfi.sv
bhv/include/cv32e40x_rvfi_pkg.sv

Made rvfi_intr multibit.
Made struct for rvfi_trap.

Multibit rvfi_intr

---

rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv

Syntax fix + IF stage fix

---

docs/user_manual/source/integration.rst

Document USE_DEPRECATED_FEATURE_SET

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv

Changed SMCLIC_ID_WIDTH default to 5

---

docs/user_manual/source/integration.rst

Fix typo in doc

---

docs/user_manual/source/intro.rst

Update CLIC version

---

docs/user_manual/source/control_status_registers.rst

Changed WARL resolution to preserved/unchanged

---

docs/user_manual/source/control_status_registers.rst

Better explanation of mtvt WARL behavior

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
bhv/include/cv32e40x_wrapper.vh
sva/cv32e40x_rvfi_sva.sv

Added rvfi_wu and rvfi_sleep signals to rvfi, fixed issue with rvfi_csr_mip_rdata signal

RVFI Sleep Signals

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
cv32e40x_manifest.flist
rtl/cv32e40x_alignment_buffer.sv
rtl/cv32e40x_clic_int_controller.sv
rtl/cv32e40x_compressed_decoder.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_int_controller.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/cv32e40x_prefetch_unit.sv
rtl/cv32e40x_prefetcher.sv
rtl/cv32e40x_wb_stage.sv
rtl/cv32e40x_write_buffer.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_alignment_buffer_sva.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_cs_registers_sva.sv
sva/cv32e40x_decoder_sva.sv
sva/cv32e40x_prefetch_unit_sva.sv
sva/cv32e40x_prefetcher_sva.sv
sva/cv32e40x_rvfi_sva.sv

Work-in-progress, do not merge.
Basic CLIC controller (without thresholds) is included.
- For CLIC, vectoring is implemented through the alignment buffer.
Core should still work in basic mode.

Basic CLIC vectoring support

---

bhv/cv32e40x_rvfi.sv
rtl/cv32e40x_wb_stage.sv

minstret rvfi reporting fix for WFI

---

rtl/cv32e40x_i_decoder.sv

Code added into i_decoder is not used yet (and it is not complete yet)
SEC clean.

First step towards merged decoder

---

rtl/cv32e40x_compressed_decoder.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_if_stage.sv
rtl/include/cv32e40x_pkg.sv
sva/cv32e40x_decoder_sva.sv

Reverting merged decoder introduction

---

docs/user_manual/source/control_status_registers.rst

Made mcounteren WARL 0x0

---

docs/user_manual/source/exceptions_interrupts.rst
docs/user_manual/source/pma.rst

Added modifiable attribute as being implied by main PMA attribute

---

rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_compressed_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/include/cv32e40x_pkg.sv

Zc C1 instructions implemented

---

rtl/cv32e40x_cs_registers.sv
rtl/include/cv32e40x_pkg.sv

Removed mscontext and mcontext CSRs

---

docs/user_manual/source/control_status_registers.rst
docs/user_manual/source/debug.rst

Removed mcontext and mscontext CSRs

---

rtl/cv32e40x_a_decoder.sv
rtl/cv32e40x_alu.sv
rtl/cv32e40x_alu_b_cpop.sv
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_clic_int_controller.sv
rtl/cv32e40x_compressed_decoder.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_bypass.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_data_obi_interface.sv
rtl/cv32e40x_decoder.sv
rtl/cv32e40x_div.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_instr_obi_interface.sv
rtl/cv32e40x_int_controller.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_lsu_response_filter.sv
rtl/cv32e40x_m_decoder.sv
rtl/cv32e40x_prefetch_unit.sv
rtl/cv32e40x_prefetcher.sv
rtl/cv32e40x_sleep_unit.sv
rtl/cv32e40x_wb_stage.sv
rtl/cv32e40x_write_buffer.sv

SEC clean (only syntax, indentation, etc. to minimize diff with CV32E40S)

Minimizing syntax/style differences with CV32E40S

---

bhv/rvfi_sim_trace.sv

Added the option of writing rvfi trace to file

---

rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_csr.sv

SEC clean
Do NOT merge to CV32E40S

Removed shadow CSR related code

---

bhv/cv32e40x_rvfi.sv
bhv/cv32e40x_wrapper.sv
bhv/include/cv32e40x_rvfi_pkg.sv
bhv/include/cv32e40x_wrapper.vh

Added mstateen3/3h which was previously forgotten.

---

rtl/cv32e40x_compressed_decoder.sv

Signed-off-by: Steffen Persvold <spersvold@gmail.com>

Remove double pkg import from compressed decoder

---

bhv/cv32e40x_rvfi.sv

Signed-off-by: Steffen Persvold <spersvold@gmail.com>

Fix Warning-[ENUMASSIGN] for Synopsys VCS

---

docs/user_manual/source/control_status_registers.rst

Table experiment 0

---

docs/user_manual/source/control_status_registers.rst

Reverts openhwgroup/cv32e40x#576

Revert "Table experiment 0"

---

docs/user_manual/source/control_status_registers.rst

Table width change

---

sva/cv32e40x_sequencer_sva.sv

Added missing assertion file.

---

rtl/cv32e40x_clic_int_controller.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
rtl/include/cv32e40x_pkg.sv

Added CLIC signals to irq_ack mechanism

---

bhv/rvfi_sim_trace.sv

Simulation performance profiling shows that the itrace module currently exhibits excessive resource usage, added parameter to selectively enable this feature if needed (disabled by default).
(Example: Identical run of corev_rand_instr_test with xcelium had its run time reduced from several hours to 2 minutes when this module was disabled)
Signed-off-by: Henrik Fegran [Henrik.Fegran@silabs.com](mailto:Henrik.Fegran@silabs.com)

Added parameter to disable itrace

---

bhv/cv32e40x_rvfi.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_sequencer.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv
sva/cv32e40x_if_stage_sva.sv

SEC clean
Todos for recent self merged PRs

Added todos related to recent PRs

---

docs/user_manual/source/rvfi.rst

Added further clarification on rvfi_dbg signal

---

bhv/cv32e40x_rvfi.sv

Added reset value for rvfi_mode

---

rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv

Removed obsolete RTL signal

---

docs/user_manual/source/intro.rst

Updated OBI to version 1.5.0

---

docs/user_manual/source/debug.rst
docs/user_manual/source/integration.rst

Added debug PC sampling interface

---

bhv/cv32e40x_rvfi.sv

Fix typo in RVFI related to pmpcfg wdata/wmask

---

rtl/cv32e40x_controller_fsm.sv
sva/cv32e40x_controller_fsm_sva.sv

Fix issue related to CLIC pointer fetch while MRET in WB

---

docs/user_manual/source/control_status_registers.rst
docs/user_manual/source/debug.rst
docs/user_manual/source/exceptions_interrupts.rst
docs/user_manual/source/integration.rst
docs/user_manual/source/intro.rst

Updates according to latest Smclic specification

---

sva/cv32e40x_rvfi_sva.sv

Added missing clock and reset to rvfi assertion/property.

---

docs/user_manual/source/debug.rst

Simplified meaning of debug_pc_* interface

---

docs/user_manual/source/control_status_registers.rst

Removed non-existing etrigger.nmi field

---

bhv/cv32e40x_core_log.sv
bhv/cv32e40x_wrapper.sv

Parameterized enablement of core_log

---

rtl/cv32e40x_alu.sv
rtl/cv32e40x_b_decoder.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_ex_stage.sv

Fix github issue #402

---

rtl/cv32e40x_cs_registers.sv

Implement dcsr.stopcount

---

rtl/cv32e40x_controller_fsm.sv

Updated debug cause priority according to debug spec v 1.0.0.

---

docs/user_manual/source/control_status_registers.rst

Typo fixes

---

yaml/csr.yaml

This is the "original" CSR definitions yaml file that we've had internally.
An up-to-date version will be in a separate PR to make the diff easier to review.

add csr definitions yaml

---

docs/user_manual/source/intro.rst

Updated Zc version to v1.0.0-RC5.7

---

bhv/cv32e40x_rvfi.sv

Clearing in_trap[stage] in  RVFI when a bubble is inserted into the stage. Also not propagating the in_trap[STAGE_WB] back to IF on debug entry if the rvfi_intr is set in the same cycle.
Fixes issue #355 on CV32E40S.

Fix for CV32E40S issue #355 (rvfi_intr)

---

docs/user_manual/source/control_status_registers.rst

Syntax fixes

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv
rtl/cv32e40x_mpu.sv
rtl/cv32e40x_wpt.sv
sva/cv32e40x_mpu_sva.sv
sva/cv32e40x_wpt_sva.sv

Added backpressure from WB to the MPU and WPT responses.

---

docs/user_manual/source/exceptions_interrupts.rst

Clarified effect of NMIs on mstatus

---

docs/user_manual/source/exceptions_interrupts.rst

Fixed inconsistency in NMI target address description for CLINT mode

---

rtl/cv32e40x_controller_fsm.sv

Not strictly needed for e40x, but makes it easier to align code with e40s.
SEC clean.

Checking privilege level when determining exception cause for ebreak

---

docs/user_manual/source/intro.rst

Updated version of RV32E to 2.0

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv

Add debug_pc_o and debug_pc_valid_o

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/include/cv32e40x_pkg.sv

Added time_i input and CSRs for reading it.

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_controller.sv
rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_core.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_cs_registers_sva.sv
sva/cv32e40x_decoder_sva.sv
sva/cv32e40x_if_stage_sva.sv
sva/cv32e40x_rvfi_sva.sv

Also guarded CLIC-specific assertions with CLIC parameter to avoid unmet covers while running formal. Removed unused port wu_wrs_i.

Bugfix: Mintstatus.mil could be set to zero when an NMI was taken.

---

rtl/cv32e40x_controller_fsm.sv

"// todo: add !ctrl_fsm_o.halt_wb below (should be SEC clean)"
SEC clean.

Removed todo in controller_fsm.

---

rtl/cv32e40x_controller_fsm.sv
rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_sleep_unit.sv
rtl/include/cv32e40x_pkg.sv

Signal rename and comment clean-up

---

rtl/cv32e40x_alu.sv

Optimized ALU to not include ZBS-specific logic if ZBS is not configured.
SEC clean with B_NONE, ZBA_ZBB, ZBA_ZBB_ZBS and ZBA_ZBB_ZBC_ZBS

Fix for issue #546

---

rtl/cv32e40x_i_decoder.sv
rtl/cv32e40x_id_stage.sv
rtl/include/cv32e40x_pkg.sv

Dead code removal

---

sva/cv32e40x_clic_int_controller_sva.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_decoder_sva.sv
sva/cv32e40x_id_stage_sva.sv

Misc syntax fixes, strengthened assertion and removed unused signals

---

rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_prefetcher.sv
rtl/cv32e40x_write_buffer.sv

Lint fixes

---

bhv/cv32e40x_rvfi.sv
sva/cv32e40x_rvfi_sva.sv

rvfi_instr_memtype
rvfi_instr_dbg
rvfi_mem_atop
rvfi_mem_memtype
rvfi_mem_dbg

Added the following signals to RVFI:

---

bhv/cv32e40x_wrapper.sv
sva/cv32e40x_controller_fsm_sva.sv
sva/cv32e40x_core_sva.sv

Issue was mostly fixed from before, but this PR should hopefully close the last items/todo's.

Fix for issue #619

---

bhv/cv32e40x_wrapper.sv
rtl/cv32e40x_alignment_buffer.sv
rtl/cv32e40x_core.sv
rtl/cv32e40x_cs_registers.sv
rtl/cv32e40x_debug_triggers.sv
rtl/cv32e40x_div.sv
rtl/cv32e40x_ex_stage.sv
rtl/cv32e40x_id_stage.sv
rtl/cv32e40x_if_stage.sv
rtl/cv32e40x_load_store_unit.sv

Lint cleanup

---

yaml/csr.yaml.m4

Added enums for exception codes and mpp.
Renamed RESERVED_XX_YY to RESVERVED<N>.
Added parameter to allow a different view of mtvec and mtvt for verification and non-verification headers.

Updates to yaml.m4

---

sva/cv32e40x_mpu_sva.sv

Fixed issue #893 mpu sva vs pma rtl mismatch

---

rtl/cv32e40x_if_xif.sv

Removed cv32e40x_pkg from cv32e40x_if_xif.

Fix for issue #882

---

sva/cv32e40x_core_sva.sv
sva/cv32e40x_cs_registers_sva.sv
sva/cv32e40x_div_sva.sv
sva/cv32e40x_ex_stage_sva.sv
sva/cv32e40x_prefetch_unit_sva.sv

Sva updates

---

bhv/cv32e40x_wrapper.sv
sva/cv32e40x_mpu_sva.sv
sva/cv32e40x_parameter_sva.sv

Part of todo fixing on e40s
a_pma_valid_config was removed since breaking this will result in compile error.

Add cv32e40x_parameter_sva.sv

---

sva/cv32e40x_controller_fsm_sva.sv

Triggered by todo fixing on cv32e40s

Add assertion a_mret_dbg_mode_illegal
