openhwgroup/cv32e40x

rtl/cv32e40x_mult.sv, sva/cv32e40x_mult_sva.sv
Removed output result mux from multiplier.
Sequentially equivalent (OBI IF checked for valid transactions only):
=> Removed result mux in multiplier

docs/user_manual/requirements.txt
Apparently the svg2pdf converter required to render inkscape files is not part of the standard RTD toolkit and therefore a 'requirements' file is required.   Note that the cv32e40s user manual will require the same file to be added - let me know if you would like a specific pull-request to add that.
Signed-off-by: MikeOpenHWGroup <mike@openhwgroup.org>
=> Add requirements file for RTD

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_register_file.sv, rtl/cv32e40x_register_file_wrapper.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv
All RF writes are now done from WB stage. Forwarding from WB to PC in case of JALR is now allowed iff WB result comes from the ALU.  SEC equivalent and passes ci_check.
=> Remove second register file write port

bhv/cv32e40x_instr_trace.svh, bhv/cv32e40x_tracer.sv, bhv/cv32e40x_wrapper.sv
No other functional changes.
Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>
=> rename E40P defines to E40X to include the tracer for core-v-verif testbench

rtl/cv32e40x_controller.sv, rtl/cv32e40x_i_decoder.sv
Add missing begin/end. Needed to allow Verible to parse the code.
=> Add missing begin, end

README.md
This PR fulfills two purposes:
1. Check to ensure I have, indeed, fixed the Travis CI problem.
2. Standardize the CONTRIBUTING section of our README.
Signed-off-by: MikeOpenHWGroup <mike@openhwgroup.org>
=> Add Commit Messages section

bhv/cv32e40x_tracer.sv
cleans up ISS usage of the tracer.  Previously the USE_ISS switch defined a macro and a run-time plusarg.  There is a corresponding PR for core-v-verif https://github.com/openhwgroup/core-v-verif/pull/548 but it is fine (and preferred) if this PR is merged first such that core-v-verif cv32e40x/dev points to this merged PR.
=> make the USE_ISS switch run-time instead of compile-time

bhv/cv32e40x_wrapper.sv
1) In order to reach some PMA-related preconditions, it is necessary to have control over the PMA parameters to the core, and hence these were added to the wrapper so they can propagate from tb top level.
2) The interfaces used to pass payloads between pipeline stages, they have modports specifying i/o direction and cannot be implicitly connected (`.*`) to modports of incompatible type, and hence the assertion bindings were instead connected to the interface instances themselves (instead of to the portlist of a submodule).
I have tested this in formal and it both elaborates and runs without problem. I also tested it in core-v-verif and it works there too (as far as the self-checking can go without step-and-compare).
=> Make the bhv wrapper formal-friendly

rtl/cv32e40x_int_controller.sv
SEC equivalent change
Removed dead code that could never get triggered due to the setting of IRQ_MASK (and we do not have any intention to change the value of IRQ_MASK; IRQ_MASK was introduced for the PULP team). Should help with code coverage.
=> Dead code removal

sva/cv32e40x_mult_sva.sv
The expected result_o of the multiplier SVAs are moved to their own signals.
This makes it much easier to inspect failures in waveforms.
=> move expected result to signals outside sva

bhv/cv32e40x_wrapper.sv
As discussed in https://github.com/openhwgroup/core-v-verif/issues/577
=> Update gate for assertions: ASSERT_ON -> COREV_ASSERT_OFF

sva/cv32e40x_mult_sva.sv
These are helper assertions created as part of formal verification.
In simulation, the overhead of these single-cycle checks should be minimal.
Tested in various formal configurations and in core-v-verif (ci_check and isa_fcov_holes).
=> Multiplier helper assertions

rtl/cv32e40x_core.sv, rtl/cv32e40x_data_obi_interface.sv, rtl/cv32e40x_instr_obi_interface.sv, rtl/if_c_obi.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_load_store_unit_sva.sv
Use structs for internal OBI control signals in preparation for parity bit addition
SEC clean
=> Use structs for internal OBI control signals

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_ex_stage.sv, sva/cv32e40x_controller_fsm_sva.sv
Removed writeback bypass for branches to achieve NRET=1 and avoid unnecessary RVFI updates before switching to the new controller.
This change allows modelling the pipeline as if all instructions retire in the writeback stage, which will be the case when the new controller updates are in.  
=> Removed writeback bypass for branches 

rtl/cv32e40x_alu.sv
Don't let adder results flow through shifter. Slightly smaller.
Initial step for the introduction of an improved shifter (including B extension additions)
SEC clean.
=> Separate adder and shifter functionality

bhv/cv32e40x_instr_trace.svh
I know this tracer is planned to be obsoleted by the rvfi tracer, but in the meantime there are 3 issues that are a bit in my way.
This PR does not necessarily _need_ to be accepted, because one can just use the CV_CORE_PATH variable in core-v-verif, but it would be nice to have the actual fixes in place.
Problem 1 is "nop". This is a pseudo instruction and this is exceptional in the tracer because there are no other pseudoinstructions. And it causes problems when diffing against other execution logs.
Problem 2 is that "fencei" is actually named "fence.i" (as seen in e.g. objdump).
Problem 3 is that "shamt" was printed wrong, because it essentially included "funct7".
=> fix tracer printing that deviates from riscv assembly format

cv32e40x_manifest.flist
Hey!
In this pull request I changed order of compilation files to avoid errors in Riviera-PRO
=> Changed order of compilation files to avoid errors

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_load_store_unit.sv
SEC clean
Note that ex_valid no longer depends on wb_ready. RVFI needs to be updated for this new semantics of ex_valid.
The same transformation will be done for if_valid and id_valid in future PRs.
=> Further ready/valid cleanup

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_div_sva.sv
Commented away assertions for not yet implemented features.
Fixed mepc and single step assertions.
Minor update to contoller, not killing ID and EX in case of single stepping, as there shall not be any instructions in those stages when the stepped instruction reaches WB.
=> Assertion cleanup

sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_ex_stage_sva.sv, sva/cv32e40x_id_stage_sva.sv, sva/cv32e40x_if_stage_sva.sv
The failing assertions are breaking core-v-verif. 
Will be reintroduced once RTL and/or assertions have been fixed.
=> Commenting away failing assertions

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_core_sva.sv
Not SEC clean (on purpose)
Performance counter events are mostly tied to 0.
minstret is NOT functional yet (but was already broken)
=> Temporarily disconnected most performance counter events. minstret is non-functional. Non-SEC clean change

rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_cs_registers_sva.sv
CSR will be read for every cycle a CSR insn is in EX.
Using ex_wb_pipe.rf_wdata in CSR read-modify-write, as this was
using the flopped rdata which does not exist anymore (and was wrong).
Purposely not SEC clean.
Passes ci_check (with ISS disabled)
=> Removed the signal csr_access.

rtl/cv32e40x_decoder.sv
On a PMA exception or bus error, the instruction word could
still contain a seemingly valid instruction, although it
had an associated exception.
Not SEC clean.
=> Suppressing *_insn_o from decoder when deassert_we is asserted.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Updates to align RVFI with new id_valid meaning.
Reverted bad code for pc_wdata modelling.
=> RVFI Updtates 

rtl/cv32e40x_controller_fsm.sv
All write enables are already disabled.
SEC clean.
=> Not killing WB stage in case of exceptions. 

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv
Moved RVFI register reads for autonomously updated registers to the EX stage in the pipe modelling. #101 
Added _n and _we  signals. #100 
=> Moved autonomously updated registers to EX stage

bhv/cv32e40x_rvfi.sv
Fixed issue where rvfi would use the exception target address for fencei pc_wdata.
=> Fixed rvfi fence instruction issue

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_id_stage_sva.sv
Suppressing *_insn bits in the decoder using deassert_we caused a path from data_rvalid_i and to the instr_ interface, breaking timing.
Added a separate deassert signal for use when IF stage has
PMA/PMP/bus_error, and uses this to deassert both write enables
and the *_special bits in the decoder. This removes the timing path
from the previous solution.
Also brought back in ID stage assertions. Work-in-progress to
reenable them and/or move them to appropriate sva files.
=> Fix for i->o path, and ID stage assertions

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Formal check for pc_wdata now passing.
Switched to calculating pc_wdata from the ID stage wdata to avoid the complex modelling required to use the IF pc during debug entry
=> RVFI: Fix for pc_wdata 

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Updated to set rvfi_trap for all synchronous traps.
Simplified and removed unused signals.
=> RVFI: Added trap conditions

rtl/cv32e40x_mult.sv
Not SEC clean, fails on cutpoint on multiplier results when
being killed.
Reduces area.
=> Made mulh_a/mulh_b independenf of valid_i.

rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_div.sv, rtl/cv32e40x_mult.sv
SEC clean (the multiplier ready_o error did not propagate onto ex_ready as wb_ready_i was ANDed into ex_ready via other paths)
=> MULT/DIV cleanup; fixed MULT ready signal; added todos

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_i_decoder.sv, sva/cv32e40x_controller_fsm_sva.sv
This will allow IF (and ID) to fill up with the jump/branch
target while EX stage may be stalled. Slightly improves performance.
Bugfix to debug entry killing of stages.
Requires an update to RVFI to properly detect jumps in ID (and possibly branches in EX)
=> Jumps and branches will only be active for one cycle.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Updated RVFI to support single jump controller update using new jump_in_id signal.
Moved mepc jump probing for mret from WB to ID stage to match core pipeline conseptually.
=> Updated RVFI to support jump once controller update

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
We could run into an issue where a single step was taken, but
another higher priority debug cause came in during DEBUG_TAKEN.
This would cause the wrong cause of debug and also possibly kill
instructions that are not allowed to be killed.
Now single step and any other cause are mutually exclusive.
Using flopped version of debug_cause during DEBUG_TAKEN
to take correct action.
=> Changed logic for debug taken.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv
Rewrote performance counters to have proper write enable and next_value. (For use in RVFI)
Added support for minstret. Notethat this uses wb_valid which factors in data_rvalid_i.
Added stall in EX if minstret is READ in EX and any instruction is valid in WB.
Updated RVFI to include dret pc in WB model and not updating EX pc in case of misaligned LSU.
ci_check is clean with one warning during debug_test (comes from verif, not RTL)
Synthesis shows around 450 gates increase compared to last hash.
This is probably due to using wb_valid in counting retired instructions.
=> Minstret updates to make clean ci_check

bhv/cv32e40x_wrapper.sv, sva/cv32e40x_mpu_sva.sv
This PR adds assertions for the PMA.
It adds a IS_INSTR_SIDE parameter to the sva module and also a few signals for connecting to the obi bus.
Then it adds the assertions themselves (according to the PMA vPlan) plus some helper logic.
Covers were added to make sure formal isn't overconstrained, to guide simulation testing, and for the insight they provide.
_NB. I did not get anyone else to review the assertions (neither the assertions alone or compared to the vPlan)._
_NB. Formal fails because all coverage is not reachable from all pma configs. I did not figure out a solution to this._
=> Pma assertions

sva/cv32e40x_mult_sva.sv
Formal regression was failing, so I took the opportunity to fix the multiplier SVAs that appear outdated after valid/ready handshaking was introduced.
Three things are changed: 1) "s_insistent_valid" replaces antecedent of input stability assertions, 2) "a_check_result_constant" was similarly updated, 3) a_check_acc_mul_value_zero was qualified with valid_i.
NB! This needs review before merging. (doesn't seem like uarch multiplier section reflects latest changes?)
Question: Should we deal with those 2 TODOs too?
=> Multiplier SVAs valid/ready update

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Updated RVFI branch probe to handle the jump-once update in the controller.
This fixes an issue where pc_wdata would not be set correctly (leading to rvfi_intr getting set) when a branch was taken during a bus stall.
=> Updated RVFI branch probe

bhv/cv32e40x_rvfi.sv
Fixed rvfi issue with the mhpevent csr register signals.
=> Fixed multidriven signal in RVFI

rtl/cv32e40x_alu.sv, rtl/cv32e40x_b_decoder.sv
Added Zbs instructions to result mux and fixed typo in instruction decoding after creating a new sanity check.
SEC Clean with B_EXT parameter == NONE.
=> B ext zbs in result mux

rtl/cv32e40x_alu.sv, rtl/cv32e40x_b_decoder.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_m_decoder.sv, rtl/include/cv32e40x_pkg.sv
Cleaned up and simplified shifter.
SEC clean both with B_EXT==NONE and with B_EXT==ZBA_ZBB_ZBS.
Slight area decrease with  B_EXT==NONE.
Some area increase with B_EXT==ZBA_ZBB_ZBS.
=> Shifter cleanup

rtl/cv32e40x_id_stage.sv
SEC clean without B extension.
Bug fix for B extension.
Divider operation uses CLZ, which in turn relies on alu_operand to be up to date, see
https://github.com/openhwgroup/cv32e40x/blob/df94dbf0ad36f88d1f65c057bb8f843a7d1692a0/rtl/cv32e40x_alu.sv#L240
=> Bug fix (when using B extension): Divider relies on ALU operand

rtl/cv32e40x_id_stage.sv
Temporary change to allow for a following SEC clean divider related update.
Not SEC clean.
This fix is related to csr_en not being suppressed for killed instructions (an issue will be filed to get that fixed).
=> Update alu operands (csr address) for CSR instructions; not sec clean

rtl/cv32e40x_cs_registers.sv
Only the lower 32 bits were written on increments.
=> Bugfix for incrementing perf counters.

rtl/cv32e40x_b_decoder.sv
Corrected use of rs2 reads in b decoder #153 
=> Corrected use of rs2 reads in b decoder

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_wb_stage.sv
-Changed rf_we_o in EX to _not_ factor in halt and kill, as this would
lead to hazards not being detected during halt. Not SEC clean as stalls are affected by this fix.
-Added a rf_we_wb_raw output to the WB stage for use in the bypass module.
-Not including the local instr valid in WB stage lsu_en and lsu_valid_o.
The above two changes are done to prevent timing paths like
controller_fsm -> bypass -> controller_fsm.
=> Path cleanup for bypass module 

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_core_sva.sv
Single_step_pending would not be evaluated in case of a pending interrupt,
possibly leading to executing two instructions in a step.
=> Moved evaluation of debug single step.

rtl/cv32e40x_controller_fsm.sv
In case of pending interrupt or debug, but not allowed to take interrupt/debug, the controller would halt ID to create an interruptible bubble later. This was done in a way that blocked any events happening in EX or WB while halting ID. Branches in EX could end up not being taken, and exceptions in WB would not be handled.
This PR addreses this issue and will enable events in EX/WB to be handled while ID stage is halted.
Passes ci_check, but is non-SEC due to the nature of the bug.
=> Bugfix: Events in shadow of interrupt/debug pending was not guaranteed to be handled

rtl/cv32e40x_controller_fsm.sv
Bugfix: Some flip flops in the controller were using the ungated clock by mistake.
Bugfix: kill_wb during DEBUG_TAKEN would kill regular ebreaks (withouth dcsr.ebreakm)
if debug was caused by an external request. Ebreaks were also killed during debug mode.
This fix does not affect RTL, but affects RVFI/RVVI.
=> Bugfixes for kill_wb during debug mode and flops using wrong clock

bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_wrapper.vh
=> Added tie-offs for rvfi signals to avoid warnings from simulators

rtl/cv32e40x_controller_fsm.sv
Single step would be signalled as pending whenever an instruction reached WB stage.
This could cause LSU instructions with late rvalid to finish after the controller
entered debug mode. This fix waits until the actual wb_valid to signal a pending
single step.
Fixes issue #187
=> Single step fix (wb_valid)

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_pma.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_ex_stage_sva.sv, sva/cv32e40x_mpu_sva.sv, sva/cv32e40x_wb_stage_sva.sv
PMA/MPU work by silabs-oivind, controller and plumbing by silabs-oysteink.
- Implements PMA check for misaligned load/store to IO regions
- Implements support for LSU PMA exceptions.
- Suppresses ex_wb_pipe.rf_we for first half of misaligned LSU instructions (only second half will write to RF)
- Suppresses WB stage rf_we in case of PMA errors.
=> LSU PMA support

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
Previously, the ID stage would update the id_ex_pipe for the second phase of a misaligned load/store while ID stage itself actually contained the next instruction. Now the load store unit does this itself. The ALU is no longer used for address calculation, and the alu_en may be set to 0 in a later change.
PR is SEC clean with one exception (see comments to diff).
=> Misaligned load/store handled inside LSU

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Removed handling of misaligned memory access which is no longer needed because of the ID/EX ready/valid handshake and moving address increment into LSU.
=> Removed handling of misaligned memory access

rtl/include/cv32e40x_pkg.sv
Changed exception code for instruction bus faults as it was not compliant to the spec.
=> Bugfix: Exception code was wrong

docs/user_manual/source/control_status_registers.rst, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_core_sva.sv
SEC clean if no CSR writes to mcause set bit mcause[5].
=> Exception code was five bits, but some codes needs six

rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_id_stage.sv
As the LSU was updated to calculate the address for misaligned load/stores, the usage of the ALU is not needed anymore.
SEC clean.
=> ALU not used for LSU instructions

rtl/cv32e40x_register_file.sv, rtl/include/cv32e40x_pkg.sv
Updated register file to not use same data type as register file wrapper to allow inserting ECC in other cores (like 40s) while keeping the register file merge-able.
=> Updated register file to a different data type to the register file wrapper

bhv/cv32e40x_rvfi.sv
Fixed issue where the rs address signals could show non-zero values when not reading.
The spec requires rs addr to be 0 when not reading.
=> Fixed RVFI rs addr issue

bhv/cv32e40x_rvfi.sv
Gated rf_wdata with address==0 because x0 is set separately from wdata in rtl (wdata and write enable can be non-zero for x0). The RVFI spec does not allow non-zero wdata for x0.
_"rvfi_rd_wdata is the value of the x register addressed by rd after execution of this instruction. This output must be zero when rd is zero."_
=> RVFI: Gated rf_wdata with address==0

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_core_sva.sv
Using Dcsr_t struct instead of invidivual bits.
=> NMI masked during single step if dcsr.stepie==1'b0

sva/cv32e40x_mpu_sva.sv
The dv testing found a bug in the assertions.
Added a clause to see that it doesn't incidentally match zero-config.
=> fix pma sva match logic

rtl/cv32e40x_div.sv, rtl/cv32e40x_ex_stage.sv
Optimized usage of valid_i in divider to remove long paths from ctrl_fsm_o.kill_ex to operand muxes in ID stage.
SEC clean.
=> Timing optimization, kill_ex through divider

rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/include/cv32e40x_pkg.sv
Removed reduntant 'deassert_we' in controller bypass. Stall signals to ID stage would prevent deasserted bits to propagate anyway.
Renamed 'deassert_we_special' to 'deassert_we'.
SEC clean.
=> Cleanup of deassert signals

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_wb_stage.sv, sva/cv32e40x_ex_stage_sva.sv
Renamed signals named *misaligned* to using 'split' instead, as this reflects the current behaviour of the LSU unit when it splits misaligned transfers.
SEC clean.
=> Renaming 'misaligned' to 'split'

rtl/cv32e40x_controller_bypass.sv
CSR stall logic did not take into account mret implicit writes when mret was in EX stage.
Removed dret from CSR stall logic as a dret kills the whole pipeline when it is in WB,
and thus no hazard from that.
=> Bugfix: Incorrect CSR stall for mret

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Fix for #204 - Debug regressions now passing with this branch.
Changed naming sceme of pipeline stages.
Added check in IF stage for traps in later stages suppressed by debug entry.
Added mstatus and mcause registers to pipeline.
=> Rvfi suppressed intr fix

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv
Stalling EX on all performance counter reads if there is a valid instruction in WB.
=> Bugfix: Did not stall for reading of instret, only minstret

docs/user_manual/source/rvfi.rst
Updated rvfi doc to specify that rvfi sees interrupts and debug entry as happening between instructions
=> Updated rvfi docs

bhv/cv32e40x_rvfi.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv
Instead of using wb_valid which factors in data_rvalid_i,
minstret is counted for the first cycle of a valid instruction in WB.
For LSU instructions with stalls on rvalid, this means we count before the instruction retires.
RVFI is altered to detect this and report correct values for the retired instruction.
=> New event for minstret counter.

rtl/cv32e40x_controller_bypass.sv
Added separate hazard detection for JR. JR will always read from RF, so the hazard logic does not include checks for rf_re when checking ID vs EX and WB for RF address.
SEC equivalent.
=> Timing opt: JR hazard detection

rtl/cv32e40x_cs_registers.sv
Performance counter event for jr_stall was not flopped, leading to bad timing.
=> Timing fix: Performance counter event not flopped

bhv/cv32e40x_rvfi.sv
=> RVFI: Added missing indexes in mhpmcounter generate loop

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_write_buffer.sv
This avoids hierarchical parameters which are not supported in some simulators.  There should be no functional change introduced with this PR.
Fixes issues with Metrics/Dsim and latest RTL hash.  See this: https://github.com/openhwgroup/core-v-verif/pull/1010#issuecomment-964357559
=> add parameters to write_buffer RTL module for SVA

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv
=> Make dcsr.nmip available on RVFI rdata. Trig rvfi_intr on NMI.

bhv/cv32e40x_wrapper.sv
No functional change, but this is needed for JasperGold UNR compile.  Otherwise the cv32e40x_core instance is black-boxed and UNR analysis fails.
=> add explicit interface connections in dot-star in wrapper

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_ex_stage_sva.sv, sva/cv32e40x_id_stage_sva.sv
Killing xif instruction via commit interface in EX, and marking instruction
as illegal.
Note that the commit_kill signal is not fully implemented yet. It will get updated in a future PR with proper killing for interrupts, debug and exceptions. Changes are expected to the way commit_kill is signalled, as for killed instructions ex_valid will not be 1.
=> Added check CSR instruction accepted by xif AND pipeline.

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_load_store_unit_sva.sv
Controller was checking toplevel OBI signals when checking for allowed interrupts/debug.
This causes issued when the write buffer accepted writes before the data_gnt_i was asserted.
Fix is to look at trans_ signals inside the LSU, before the MPU. Added a "interruptible" outout
from the LSU instead of looking at lsu_en i ex/wb inside the controller.
=> Fix for issue #317.

rtl/cv32e40x_alu.sv, rtl/cv32e40x_b_decoder.sv, rtl/include/cv32e40x_pkg.sv
Decoding of sext.h was also fixed, as bits[31:25] did not match the specification.
=> Adding missing zext.h instruction [B_EXT]

rtl/cv32e40x_ex_stage.sv
Illegal CSR instructions were not properly handled.
Bug introduced by recent eXtension interface implementation.
=> Fixed issues #332 and #333

rtl/cv32e40x_compressed_decoder.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_decoder_sva.sv
Not all illegal compressed instructions generated an uncompressed instruction word. Fixing this hole enables synthesis to optimize
the decoder in ID stage by removing two LSBs.
Not SEC clean due to stalls caused by rs1/rs2 fields in illegal compressed instructions.
SEC clean if compressed instruction word is passed through predecoder with two LSB set to 1.
=> Optimize predecoder/decoder for illegal compressed instructions

rtl/include/cv32e40x_pkg.sv
=> Remove unused constant

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv
Removed two obsolete TODOs from toplevel.
Refactored usage of dcsr.step and dcsr.stepie from cs_registers to the controller_fsm.
SEC clean.
=> Todo removal 2

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_lsu_response_filter.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
LSU response filter is now outputting what type of load/store is associated with a bus error.
Also routing the bus_resp through the filter for cleaner code.
Controller now gets two bits from the load_store_unit, one for qualifying an NMI and one for
signaling if it is for a load or store.
=> Fix for issue #343

rtl/cv32e40x_b_decoder.sv
Instruction sext.b used wrong encoding, resulting in illegal instruction.
=> Bugfix: sext.b used wrong encoding

docs/user_manual/source/pma.rst, docs/user_manual/source/rvfi.rst
Updated RVFI documentation for rvfi_trap[13:12]
Fixed issue with reference when building from clean workspace.
=> Updated rvfi_trap documentation

rtl/cv32e40x_cs_registers.sv
Simplified mcountinhibit register implementation to make mcountinhibit_n signal show true write value.
This is a fix for #347, perf_counters_instructions test passes on strichmo/pr/mcountinhibit fork with this change.
SEC clean change.
Slight area improvement (less than noise margin).
=> mcountinhibit simplification

bhv/cv32e40x_rvfi.sv, sva/cv32e40x_rvfi_sva.sv
This is a fix for #342
Added missing support for reporting single step with rvfi_trap.
Added assertion that would have caught this missing feature
=> Fix for issue #342

rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv
Removed TODO's suggesting not to propagate PC to EX and WB if there are no exceptions.
We can't do this because asynchronous events (e.g. interrupt or debug req) need valid PC's in all stages to store in mepc or dpc.
=> Remove TODO's

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, sva/cv32e40x_controller_fsm_sva.sv
Removed logic intended for preserving address of a faulted load or store for use in mtval CSR.
This code was not used, and it would not work in the current state as it could overwrite the
faulted address.
Added assertion to check max number of retired instructions after an NMI becomes pending.
This uncovered a case where the result of a faulted load may actually be used.
Bugfix: Halting ID stage in the same cycle as the bus error arrives, allowing max 1 extra retirement
after the faulted LSU instruction..
Non-SEC due to the bugfix.
=> Removal of todo's and currently unused logic

rtl/cv32e40x_alignment_buffer.sv
Fixing lint warning for bit widths in the alignment buffer.
SEC clean.
=> Fix for issue 367

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_if_stage.sv, rtl/include/cv32e40x_pkg.sv
PR consists of 3 commits:
ccd2871: SEC clean. Move PC mux from CS registers to controller FSM
f743203: Not SEC clean. Update the halt/kill behavior upon fencei. This is not SEC clean because the previous implementation would try to fetch an (unneeded) instruction when IF was killed when fencei entered WB. Halting IF (not killing) prevents this redundant instruction fetch.
5069951: SEC clean. Use output from PC mux in controller FSM upon fencei.
=> Add PC mux in cv32e40x_controller_fsm. use this mux for fencei PC and exception PC

rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv
Always reads zero, writes are ignored.
Should fix issue #395.
=> Added mising CSR tcontrol at address 0x7A5.

rtl/cv32e40x_core.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv
This is a patch for issue #393.
The IF stage increments XIF instruction IDs when the `issue_valid`
signal of the XIF issue interface is asserted.  However, if the ID stage
is stalled but the instruction currently held in it has been offloaded
and already accepted by the coprocessor, then `issue_valid` signal is no
longer asserted and thus the same instruction ID is reused for the next
offloaded instruction.
This patch fixes the problem by introducing a new signal that indicates
whether the instruction currently held in the ID stage is being
offloaded, with that signal remaining asserted if the coprocessor has
already accepted an instruction. The new signal informs the IF stage
whether the instruction currently in ID is being offloaded, in which
case the instruction ID is incremented.
=> Fix XIF ID increment logic (#393)

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
Three instructions could be retired between a bus error and the taken NMI.
Fixed RTL to halt ID stage earlier, and updated the associated assertion
to take into account that bus errors for bufferable writes may come between
instructions.
=> Fix for issue #398.

rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv
Suppressing csr_en for nullified instructions instead of csr_op to avoid affecting stall cycles with nullified instructions.
This no longer results in timing issues.
Fix for #156
=> Suppressing csr_en for nullified instructions 

sva/cv32e40x_core_sva.sv
Fixed signal name update that was missed in previous commit
=> Updated signal name in sva

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv
=> Parameterized clic irq id

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_pma.sv, rtl/cv32e40x_write_buffer.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_mpu_sva.sv, sva/cv32e40x_write_buffer_sva.sv
Rename pma_region_t to pma_cfg_t. For consistency.
=> Rename pma_region_t -> pma_cfg_t in RTL and SVA

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_load_store_unit.sv
Fixed rvfi issue where rvfi_intr could get set due to an mret that is killed before getting to writeback. 
Fixed rvfi branch handing (#452 )
Also fixed formal warning in load-store unit.
=> RVFI bugfixes

rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/if_xif.sv, sva/cv32e40x_load_store_unit_sva.sv
This PR adds the XIF memory interfaces (i.e., the [memory request/response](https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/x_ext.html#memory-request-response-interface) and the [memory result](https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/x_ext.html#memory-result-interface) interfaces) to CV32E40X.
The first commit replaces the [`size` field in the XIF interface definitions](https://github.com/openhwgroup/cv32e40x/blob/380b9fd6dff586d332886e0eaa875e9aafa54ca6/rtl/if_xif.sv#L86) with a byte enable mask as discussed here: https://github.com/openhwgroup/core-v-xif/issues/17
The second commit implements the base functionality required to handle memory requests by a coprocessor. Memory requests received via the XIF memory interface are converted into memory …
=> Add XIF memory interface

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/exceptions_interrupts.rst, docs/user_manual/source/integration.rst, docs/user_manual/source/intro.rst
=> Increased allowed SMCLIC_ID_WIDTH range. Moved to OBI v1.4

rtl/include/cv32e40x_pkg.sv
=> Updated typedefs for CSR registers to match new fields in the user manual

docs/user_manual/source/rvfi.rst
=> Added sleep signals to rvfi documentation

rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv
Making mstatus.mpie and mstatus.mpp accessible via mcause.
SEC clean with SMCLIC=0
=> CLIC: Spec chapter 5.1

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_core_sva.sv
CSRs mie and mip appear as hardwired to zero when SMCLIC = 1.
Writes are ignored.
SEC clean when SMCLIC = 0
=> CLIC: Spec chapter 5.3

sva/cv32e40x_rvfi_sva.sv
Made assertions checking consistency between the MIE/MIP CSRs and the sleep signal
=> Added RVFI assertions

bhv/cv32e40x_rvfi.sv, rtl/cv32e40x_clic_int_controller.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_wb_stage.sv
MNXTI functionality should now be in.
Tested basic functionality of reading correct pointer addresses for pending interrupts when changing levels in the memory mapped registers.
SEC clean for SMCLIC=0
=> Implementation of mnxti

rtl/cv32e40x_compressed_decoder.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/include/cv32e40x_pkg.sv
Moved first two isntructions from predecoder to main decoder.
Predecoder is still used to cause the register file operand reads.
SEC clean
=> Moved two instructions from predecoder to decoder

bhv/cv32e40x_wrapper.sv, constraints/cv32e40x_core.sdc, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_if_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_rvfi_sva.sv
SEC equivalent if USE_DEPRECATED_FEATURE_SET = 0.
Did not run assertion check flow as that is currently not compiling. 
Note that the a_rvfi_nmip_nmi_handler was fixed as well. It was not correct for either setting of USE_DEPRECATED_FEATURE_SET. I don't know why these assertions are excluded from formal runs (I will check with Halfdan).
=> Removed nmi_addr_i; removed USE_DEPRECATED_FEATURE_SET parameter

rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv, sva/cv32e40x_decoder_sva.sv
Changed interface of cv32e40x_decoder to be in line with the one used in cv32e40s.
Moved (temporary) instruction merge code from ID stage to the decoder.
Trailing whitespace removal.
=> Decoder interface change

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_prefetch_unit.sv, rtl/cv32e40x_prefetcher.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_decoder_sva.sv, sva/cv32e40x_prefetch_unit_sva.sv, sva/cv32e40x_prefetcher_sva.sv
CLIC SHV  + single stepping should now work.
Disabled trigger matches for CLIC pointers (awaiting spec change for CLIC in this regards)
Various other small bugfixes and assertion updates.
=> Bugfixes after running formal 

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Bugfix for RVIF handling of WFI. Was not gating WFI in WB with ex_wb_pipe.sys_en.
=> Bugfix: RVFI was not qualifying WFI with sys_en.

sva/cv32e40x_controller_fsm_sva.sv
Fixed some helper logic in controller_fsm_sva to properly deal with types for obi request/gnt/rvalid.
=> Assertion update for obi types

rtl/cv32e40x_compressed_decoder.sv, rtl/cv32e40x_decoder.sv, sva/cv32e40x_decoder_sva.sv
SEC clean (trade off readability vs. speed/gates)
Did not try out newly added assertions
=> Speeding up decoder

bhv/cv32e40x_dbg_helper.sv
Changed from unpacked to packed array for rf_raddr within the dbg_helper module to help verilator support.
=> Fix for issue #407

docs/user_manual/source/pma.rst
=> Added PMA alignment restriction if X_EXT = 1

rtl/cv32e40x_compressed_decoder.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_if_stage.sv
=> Implemented all C0 instructions from Zc v 0.70.1.

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/load_store_unit.rst
=> mtvec.mode is a 2-bit WARL bitfield. Require write buffer flush before retiring fence.i

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
=> Fixed connection to sys_mret_id to rvfi inside wrapper.

docs/user_manual/source/exceptions_interrupts.rst
Do not merge into 40S (there is a separate PR there)
=> Reordered content in exceptions and interrupts chapter for clarity

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_write_buffer.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv
- Removed logic related to NMI for CLIC pointers and write buffer 'empty' output.
=> Further removal of CLIC pointers using data access.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_wb_stage.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv
Misaligned load/stores now signal wb_valid for both transfers. The last transfer gets marked with "last_op = 1".
SEC clean.
=> wb_valid for all suboperations

rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_core_sva.sv
Table jumps could we using the wrong value of JVT in case a younger instruction in the pipeline is writing to JVT while the table jump is reading it. Fixed issue and also added assertion for the scenario.
SEC clean when ZC_EXT=0
=> Table jump stall

docs/user_manual/source/atomics.rst, docs/user_manual/source/index.rst, docs/user_manual/source/load_store_unit.rst
=> Documented Atomics extension

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_rvfi_data_obi.sv, bhv/cv32e40x_rvfi_instr_obi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv, cv32e40x_manifest.flist, rtl/cv32e40x_alignment_buffer.sv, sva/cv32e40x_rvfi_sva.sv
SEC clean (minor RTL updates are just syntax; behavioral updates mostly)
New assertions pass if PMA is not included (-rc=pma_1) and fail otherwise.
Work is not complete yet:
- need to fix tracking for the scenario with enabled PMA
- need to actually feed OBI signals through RVFI
- need to add data OBI tracking
Reason for an initial PR is to easily be able to make an additional PR with some aligner related RTL updates (while keeping these RTL updates in a separate PR).
=> Initial version of RVFI OBI tracking

rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_pma.sv, rtl/cv32e40x_prefetcher.sv, sva/cv32e40x_alignment_buffer_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_if_stage_sva.sv, sva/cv32e40x_mpu_sva.sv, sva/cv32e40x_prefetcher_sva.sv
SEC clean
This is a follow up to https://github.com/openhwgroup/cv32e40x/pull/560 (it will help to make the RVFI OBI tracking less dependent of probing the alignment buffer signals). Needed to fix (unnecessarily strict) assertions as part of this.
=> Moved instruction address word alignment to core boundary

rtl/cv32e40x_clic_int_controller.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_if_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
When JVT is being written in WB, all stages are halted until the write is done. A pipeline flush and refetch of PC+4 is then performed to ensure any table jumps in the pipeline will use the correct JVT value.
SEC clean when ZC_EXT=0
Not SEC clean when ZC_EXT=1 due to different halt/flush conditions.
=> Pipeline flush for JVT writes

rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv
SEC clean (fixes RVFI issue by fixing RTL signal only used in RVFI hookup)
Needs to be merged to 40S
=> Fix mstatush_n for RVFI hookup

rtl/cv32e40x_controller_fsm.sv
=> Refactored interrupt_allowed and halt_id logic.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_sequencer.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_id_stage_sva.sv, sva/cv32e40x_if_stage_sva.sv, sva/cv32e40x_sequencer_sva.sv
Integrating sequencer with pipeline.
- Not allowing interrupts to break sequences
- Not allowing NMI to break sequences
- Not allowing debug to break sequences
- Exception will be taken on any operation from WB
- Halting of ID stage not allowed if ID stage is in the middle of a sequence (to avoid deadlocks where the core is waiting for a sequence to finish before it can take an interrupt)
- Updated logic to halt IF due to single step to account for multiple operations from the sequencer
-
SEC clean when localparam ZC_EXT = 0 and correct OBI behavior is assumed (no instr_rvalid_i before instr_req_o)
=> Sequencer integration

rtl/cv32e40x_if_stage.sv
- No prefetch_ready handshake on tbljmp. Table jumps will either generate a pc_set and kill_if when they reach ID, or they will get killed (which also implies kill_if and a new pc_set).
- Sequencer will not get valid_i on trigger matches. Matched instruction will be first && last and enter debug before first operation is retired.
- Deasserting tbljmp for trigger matches (similar to how all write enables are deassert in ID for trigger matches).
Above three changes are needed for E40S PC hardening logic, and are added to E40X for code consistency.
Not SEC clean due to different prefetch_ready which makes the instruction bus differ in SEC.
=> Updates to Zc handling in IF stage

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/integration.rst
=> Restricted misa CSR and X_MISA parameter to always have D and Q bits 0

docs/user_manual/source/intro.rst
=> Updated Zc extension version to v0.70.5

rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_wb_stage.sv, rtl/if_xif.sv
Hi,
This PR updates the XIF interface definition, the LSU, and the WB stage to the changes in openhwgroup/core-v-xif@e65cc88 and openhwgroup/core-v-xif@6c257cd.
XIF memory requests are no longer aligned by the CPU. Instead, data and byte enable signals (`wdata`, `rdata`, and `be`) are assumed to be already aligned to the width of the memory bus (any required alignment and splitting must be performed by the coprocessor).
The XIF memory request's transaction attribute `attr[1]` (indicates whether the request is naturally aligned) is included in `misaligned_access` and thus made available to the PMA.
**Question:** I am unsure how to handle the other transaction attribute (`attr[0]`, indicating whether the transaction was modified by the coprocessor) in CV32E40X. In the current PR this …
=> Update XIF interface

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv
SEC clean (with/without SMCLIC)
=> Unifying code with CV32E40S

docs/user_manual/source/control_status_registers.rst
=> Fixed bitfield description in mtvec CSR for CLIC

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/exceptions_interrupts.rst
=> Redefined NMI target address for basic non-vectored mode and CLIC mode

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, sva/cv32e40x_controller_fsm_sva.sv
Swapped the RTL detection logic with the logic used in the SVA file. This is done to avoid a combinatorial loop is using 'seq_valid'  to calculate first_op of the IF stage.
First PR of a series to clean up Zc code and in particular handling of first_op and last_op.
SEC not determined at the time of PR (for both ZC_EXT=0 and ZC_EXT=1)
=> Changed logic for sequence progress detection

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_sequencer.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
Sequenced instructions and table jumps will proceed to ID stage regardless of MPU status and bus error.
Using deassert_we logic in ID stage to avoid side effects.
Added abort_op bits to all stages. These gets set whenever a known exception or trigger match is active in the stage where they occur.
Keeping ZC_EXT localparam as 0 until verification is ready to enable it.
NOT SEC clean as the difference in deassertion logic impacts the prefetcher.
=> Removed exception checking in IF stage

rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv
Fix for https://github.com/openhwgroup/cv32e40x/issues/640
=> Fix mcause.mpp indices

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Fix for https://github.com/openhwgroup/cv32e40s/issues/281
=> RVFI update. Sample data_addr and data_wdata in EX stage before write buffer

rtl/cv32e40x_compressed_decoder.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_sequencer.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_if_stage_sva.sv, sva/cv32e40x_sequencer_sva.sv
Tablejump pointers are handled within the sequencer, but bypass the internal FSM of the sequencer.
SEC clean for both values of ZC_EXT.
=> Moved decoding of tablejumps to the sequencer

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv
Halting EX stage if a CSR write in WB may enable interrupts and at the same time there is an LSU instruction in EX. Fix implemented for both CLIC and basic interrupt mode.
Issue can still occur when X_EXT=1. Fixing this would also need several other fixes for the X-interface.
=> (Partial) fix for issue #325.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_clic_int_controller_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Blanking interrupts for one cycle after a Load/Store instruction leaves WB.
Refactored some CLIC assertions (new file for clic_int_controller_sva)
=> Fix for issue #507

rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_cs_registers_sva.sv
Horizontal traps (exceptions) to the same privilege level will now keep the value in mintstatus.mil stable. Previously this was updated to whatever value was on ctrl_fsm.irq_level regardless of exceptions or interrupts being taken.
=> Fix for issue #499.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_prefetch_unit_sva.sv
When an mret is executed when mcause.minhv==1, the controller will allow EX and WB to flush before restarting the pointer fetch, using the value in mepc as value for the pointer location.
=> Fix for issue #498.

rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_cs_registers_sva.sv
Removed instances for mscratchcsw and mscratchcswl CSRs. These CSRs now conditionally operate on mscratch according to the CLIC spec.
=> Fix for issue #589.

sva/cv32e40x_rvfi_sva.sv
The assertion mentioned in the issue is now included regardless of the SMCLIC parameter. Assertion passes for both SMCLIC=0 and SMCLIC=1.
The cause for the failing assertion has already been fixed in earlier commits.
=> "Fix" for issue #494.

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_wb_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Split ctrl_fsm_o.halt_wb in two, with ctrl_fsm_o.halt_wb acting as normal for all cases except during sleep. During sleep, ctrl_fsm_o.halt_limited_wb will be used to make sure the WB stage does not retire any instructions.
Assertions were added to make sure no CSR instruction can be in WB while halt_limited_wb is set.
SEC clean.
Fixes timing issues.
=> Splitting halt_wb to fix timing issues when waking from SLEEP

bhv/rvfi_sim_trace.sv
=> Fix performance issue in rvfi_sim_trace and enable it by default.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, sva/cv32e40x_rvfi_sva.sv
Updated RVFI to not clear in_trap in IF when a CLIC pointers goes from ID to ID. Fixes issue #300 on CV32E40S.
=> Fix for missing rvfi_intr on CLIC SHV interrupts.

rtl/cv32e40x_i_decoder.sv
Updated CSR access to mscratchcsw[l] to also flag illegal instruction if rs1 == x0.
=> Mscratchcsw[l] illegal if rs1==x0 with CSRRW.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/include/cv32e40x_pkg.sv
- Added SUBMODE field to mtvec - tied to 0 (SEC CLEAN)
- CSR accesses to mnxti with immediate bits 0, 2 or 4 set will cause an illegal instruction
- Number of implemented bits in mintthresh depend on SMCLIC_INTTHRESHBITS. Unused bits are tied to 1. Implemented bits are left justified. (SEC CLEAN when SMCLIC_INTTHRESHBITS = 8)
- mscratchcsw now depend om mstatus.mpp instead of mcause.mpp (SEC CLEAN)
- Removed instantiated CSR for read-only mclicbase (not directly relevant to PR 680)
From earlier PR #686 and #687, the legalness of accesses to mscratchcsw[l] are updated to reflect the CLIC spec.
=> Updates related to PR #680

rtl/cv32e40x_cs_registers.sv
Fix for https://github.com/openhwgroup/cv32e40s/issues/277
This will be merged over to cv32e40s.
=> Clear mstatus.mprv when entering user mode through dret

rtl/cv32e40x_cs_registers.sv
Changed calculation of interrupt threshold output and mcountinhibit_mask to avoid possible zero-replication errors.
SEC clean.
- Checked with NUM_MHPMCOUTERS values [0,7,29]
- Checked with SMCLIC_INTTHRESBITS values [1,2,8]
=> Removed possible zero-replication code

rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Note that the minhv handling (still) contains an error where a state change due to (mret->pointer_fetch->mcause.minhv) can be done even though the mret instruction is killed. A fix for this will be done separately.
=> Merge minhv handling from CV32E40S

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Moved clearing of mcause.minhv for successful pointer fetches from ID to WB. This aligns with other state changes that also happens from WB. Should fix issue where a killed mret could still lead to clearing of mcause.minhv.
Remoted separate single_step_pending flag for pointer fetches, as single step now can use the wb_valid for the pointer to signal step entry.
=> mcause.minhv clear from WB stage

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_bypass.sv, sva/cv32e40x_controller_fsm_sva.sv
Including CLIC pointers in CSR hazard detection. Pointers with no exceptions clear mcause.minhv from WB. Any instructions reading mcause should be stalled in ID for this case.
Implemented in the same was as the existing CSR stalls, not checking for actual csr address read vs address written. There is a todo in the code to make this stall more specific in the future.
=> CSR stall on CLIC pointers writing to mcause.minhv

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_register_file.sv, rtl/cv32e40x_register_file_wrapper.sv, rtl/cv32e40x_sequencer.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_id_stage_sva.sv, sva/cv32e40x_register_file_sva.sv
SEC clean when parameter RV32=RV32I
=> Add support for RV32E

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv, rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_prefetch_unit.sv, rtl/cv32e40x_sequencer.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_decoder_sva.sv, sva/cv32e40x_if_stage_sva.sv, sva/cv32e40x_prefetcher_sva.sv, sva/cv32e40x_rvfi_sva.sv, sva/cv32e40x_sequencer_sva.sv
POINTER_FETCH fsm state replaced by a separate state flop. Controller stays in FUNCTIONAL while handling CLIC SHV interrupts.
Mret which restarts CLIC pointer fetch due to mcause.minhv and mcause.mpp will now get its 'last_op' bit set to 0 in the ID stage, and the following CLIC pointer will complete the sequence. CSR updates only happen when the pointer reaches WB.
NOT SEC clean
- Master has bugs (possible deadlock while single stepping mret with CLIC pointers, wrong pipeline stage used for excluding CLIC pointers from incrementing minstret).
- Minstret will now only update for mret when the CLIC pointer is done (or when the mret reaches WB if no CLIC pointer fetch is restarted)
=> Removed POINTER_FETCH state from controller_fsm

rtl/cv32e40x_controller_fsm.sv
Negating id_ex_pipe.instr_meta.clic_ptr was removed by mistake in the previous PR.
=> Bugfix: minstret would only update for clic pointers

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_debug_triggers.sv, rtl/include/cv32e40x_pkg.sv
Added support for DBG_NUM_TRIGGER parameter.If 0, the debug_triggers module will not be instantiated and any access to trigger CSR will result in an illegal instruction.
debug_triggers will instantiate DBG_NUM_TRIGGERS instances of tdata1 and tdata2 and perform instruction address match checks for any enabled triggers.
Converted trigger type 2 (mcontrol) to 6 (mcontrol6) and updated trigger match to take EXECUTE and M bit into account. (Passed modified debug_trigger_test). Reset value for tdata1 is updated to reflect mcontrol6.
Without the conversion of mcontrol -> mcontrol6, this PR is SEC clean when DBG_NUM_TRIGGERS=1.
=> Added support for DBG_NUM_TRIGGERS parameter

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_core.sv
ZC_EXT localpram in toplevel is now 1, and sequencer assertions bound by default in the wrapper
=> Turned on ZC_EXT.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_debug_triggers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Implemented trigger type 0x5 (exception trigger) and 0xF (disabled trigger).
- WARL handling of both tdata1 and tdata2 to ensure no invalid combination of tdata1 and tdata2 can occure.
- Exception trigger uses same logic as single step debug entry to allow for exception side effects to happen before debug entry is done.
=> Trigger types 0x5 and 0xF

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_load_store_unit.sv, sva/cv32e40x_load_store_unit_sva.sv
split_q should always be 0 when a new LSU instruction enters EX (currently passes)
trigger_match_0_i should remain stable when an LSU instruction is in EX but not yet allowed to progress to WB (currently fails)
=> Added assertions for LSU split_q and trigger_match_0_i

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, cv32e40x_manifest.flist, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_wb_stage.sv, rtl/cv32e40x_wpt.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_load_store_unit_sva.sv, sva/cv32e40x_wpt_sva.sv
Refactored watchpoint trigger behavior.
- Instead of gating valid_0_i in the LSU, there is a new module cv32e40x_wpt that sits between the 'aligner' and the MPU in the LSU. This module will let un-triggered accesses through and 'consume' those with watchpoint triggers.
- WPT will return the trigger match with WB timing, as the MPU returns mpu status today.
- Controller was updated to handle the new timing of the trigger match/abort_op signals.
=> Watchpoint triggers refactor

rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_prefetch_unit.sv, rtl/cv32e40x_prefetcher.sv, rtl/include/cv32e40x_pkg.sv
Introduced privilege level in alignment_buffer, prefetcher and and pipeline registers structs to better align with CV32E40S.
SEC clean.
=> Initroduced privilege level to align with CV32E40S.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv
Removed dependency on other pending debug causes when setting 'pending_single_step.
Updated setting of debug_cause_n, all possible causes are now in the priority (0.13.2, will be updated for 1.0.0). When all casues are set, some code cleanup faning into kill_wb from the DEBUG_TAKEN state was possible.
Updaed RVFI to account for the possibility of have pending_single_step active at the same time as there can be pending async or sync debug reasons.
=> Single step and debug cause cleanup

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
Core will now wake up if there is a pending NMI.
=> Fix for cv32e40s issue #350 (common with cv32e40x).

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
Taking an NMI while single stepping and dcsr.stepie is set causes the core to reenter debug mode without retiring any instructions.
=> Fix for issue #711.

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, sva/cv32e40x_controller_fsm_sva.sv
Removed sticky debug request (debug_req_q)
Updated assertion a_fencei_hndshk_req_when_fencei_wb to accomodate changes.
=> Fix for issue #341.

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/debug.rst
Updated description of the debug_req_i signal.
Updated description of legal CSR instruction for accessing the mnxti CSR.
=> User manual updates for mnxti and debug_req_i descriptions

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_debug_triggers.sv, rtl/cv32e40x_i_decoder.sv, rtl/include/cv32e40x_pkg.sv
Added WARL resolution functions for the following CSR fields:
- mstatus.mprv
- mtvec.mode (CLIC mode)
- mtvec.mode (CLINT mode)
- mcontrol6.u
- etrigger.u
- dcsr.ebreaku
SEC clean when SMCLIC=1
NOT SEC clean when SMCLIC=0 due due to a known bug in mtvec.mode WARL handling.
=> WARL resolution functions

rtl/cv32e40x_debug_triggers.sv
Attempts to write an unsupported trigger will now cause tdata1 to become a disabled trigger (type 0xF) instead of keeping its old value.
=> Trigger type WARL resolution (0xF)

rtl/cv32e40x_controller_fsm.sv, rtl/include/cv32e40x_pkg.sv
Added privilege level check to ebreak with dcsr.ebreakm. Will get optimized away during synthesis, but aligns code better with cv32e40s.
Small update to mtvec_mode_clic_resolve function which causes warnings on bit widths.
SEC clean
=> Added privilege level check to ebreak with dcsr.ebreakm

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_if_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_rvfi_sva.sv
CLINT vectored: mtvec offset 15
CLINT non-vectored: mtvec offset 0
CLIC mtvec offset 0
=> Updated targets for NMI.

rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_cs_registers_sva.sv
RVFI didn't always get the correct write values, and the aliasing was only working from mcause to mstatus and not the other way.
The three bits are now duplicated in both mcause and mstatus, and are always written simultaneously. Assertions are added to check that mcause and mstatus always write at the same time, and that the *_rdata.mpp/mpie fields are always the same.
SEC clean
=> Updated aliasing of mpp and mpie between mcause and mstatus.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, sva/cv32e40x_cs_registers_sva.sv
Fixed some feedback that was previously not incorporated. 
Added possibility to control the RVFI _rmask values. These will always be all ones for most CSRs, but for mscratchcsw[l] and mnxti the rmasks will only be set whenever the according CSR is actually accessed in WB.
=> Fix for issue #668

docs/user_manual/source/debug.rst
Removed figures 14 and 15 from the debug chapter.
Added not about level sensitivity of debug_req_i and that it should be kept asserted until the core can be observed to be halted.
=> Update to debug description

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_alignment_buffer_sva.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_prefetch_unit_sva.sv
Removed BOOT_SET state from controller_fsm.
Checking for debug_req_i in RESET state to enable going directly to debug mode from RESET without fetching any instructions.
=> Fix for issue #410

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_clic_int_controller.sv, rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
When waking up from sleep (exiting FSM state SLEEP), the cause of wakeup is now flopped to enable the FSM to take the action according to the wakeup reason, although there may be higher priority events appearing after the wakeup.
=> Fix for issues #365 and #361 on cv32e40s.

docs/user_manual/source/control_status_registers.rst
=> Clarified effect of X_MISA on the misa CSR

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_i_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_pc_target.sv, rtl/include/cv32e40x_pkg.sv
Reusing adder in the pc_target module to compute the tablejump address based on the JVT value and the table index from the instruction.
=> Fix for issue #751. Changed JVT alignment from 1k to 64 Bytes

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Update RVFI calculation of pc_wdata in ID and EX. Adding support for pointers and table jumps.
Fix for https://github.com/openhwgroup/cv32e40s/issues/342
=> Update RVFI calculation of pc_wdata in ID and EX.

sva/cv32e40x_cs_registers_sva.sv, sva/cv32e40x_ex_stage_sva.sv
Added assertions to check that no CSR flop outputs change if a set or clear operation is being performed when rs1==0.
Updated assertion that checks branch target stability to factor in 'last_op' when terminating the check, and removed dependency on kill_ex in the left hand side.
=> Assertions for issue #302 (e40s)

bhv/cv32e40x_wrapper.sv, sva/cv32e40x_debug_triggers_sva.sv
Added assertions to instantiated trigger CSRs in debug_triggers. Checking that no bits change on set/clear with all-zero write data.
=> Added set/clear assertions for trigger CSRs.

rtl/cv32e40x_compressed_decoder.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_sequencer.sv
Removed Zcmb
Adjusted split between cm.jt (32 indices) and cm.jalt (224 indices)
Added check for jvt.mode when decoding cm.jt and cm.jalt. (This change is SEC clean)
=> Update to Zc v1.0.1

rtl/cv32e40x_debug_triggers.sv, rtl/include/cv32e40x_pkg.sv
Adding label do-not-merge as we may need an ISS update due to the changes in tdata1 legal values and reset value.
=> Added trigger type 2 (mcontrol)

rtl/cv32e40x_controller_fsm.sv
Not SEC clean as there is a difference when an exception trigger is enabled. Old cold would get an exception trigger that caused debug entry while new code would not get an exception and enter debug with cause=ebreak.
=> Not flagging exception for ebreak if dcsr.ebreakm==1.

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
Refactored debug_cause decision.
1: Removed large ternary debug_cause assignment, replaced by priority between synchronous debug causes only.
2: Moved most priority logic into FSM, setting debug_cause_n whenever ctrl_fsm_ns == DEBUG_TAKEN.
=> Fix for issue #745

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_wb_stage.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_cs_registers_sva.sv, sva/cv32e40x_load_store_unit_sva.sv, sva/cv32e40x_mpu_sva.sv, sva/cv32e40x_rvfi_sva.sv, sva/cv32e40x_wb_stage_sva.sv
Introduced 'DEBUG' parameter. When not enabled, no debug CSRs will be implemented and the external debug_req_i will be ignored.
Restructured lots of sva-file to accomodate the new parameter.
=> DEBUG parameter

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_a_decoder.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_decoder.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_pma.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_decoder_sva.sv, sva/cv32e40x_mpu_sva.sv
Split A_EXT parameter into A_NONE, ZALRSC and A. Updated a_decoder according t othe new split A_EXT parameter.
Added wu_wrs_i pin, currently not used.
=> Split A_EXT parameter and added wu_wrs_i pin.

docs/user_manual/source/atomics.rst, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/integration.rst, docs/user_manual/source/load_store_unit.rst
Updated user manual to describe the updated A_EXT parameter, and added a note about mret instructions not clearing reservation sets.
=> User manual update for A_EXT.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_debug_triggers.sv, sva/cv32e40x_debug_triggers_sva.sv, sva/cv32e40x_rvfi_sva.sv
Misaligned atomic instruction will get rvfi_trap.cause_type == 0
Aligned atomic instructions to non-atomic PMA regions will get rvfi_trap.cause_type == 1
Note that AMOs are not properly supported within RVFI  yet. This will be implemented once verification is closer to start looking at AMOs.
=> RVFI updates for A_EXT

bhv/cv32e40x_rvfi.sv, bhv/include/cv32e40x_rvfi_pkg.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_pma.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_mpu_sva.sv, sva/cv32e40x_rvfi_sva.sv
These will only be used for misaligned atomics which are not otherwise blocked by the PMA.
SEC clean when A_EXT=A_NONE and the new exception codes are not allowed to cause exception triggers (tdata2_rdata may propagate and lead to counter examples).
=> Added exception codes 0x4 and 0x6 misaligned atomics.

rtl/cv32e40x_controller_fsm.sv
Not allowing interrupts, nmi, async debug or sync debug while the controller is in the SLEEP state.
SEC clean.
=> Fix for CV32E40S issue #403

bhv/cv32e40x_rvfi.sv
Fixed issue with rvfi write masks for tselect, tinfo and tdata3 (https://github.com/openhwgroup/cv32e40s/issues/417).
=> Fixed rvfi wmask issue for tselect, tinfo and tdata3

bhv/cv32e40x_wrapper.sv, sva/cv32e40x_load_store_unit_sva.sv
Added assertion to check that the MPU will always block misaligned atomics.
Should enable closing of issue #388.
=> Assert for misaligned atomics

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_rvfi_data_obi.sv, bhv/cv32e40x_wrapper.sv
Only updating rvfi_mem_rmask and rvfi_mem_wmask if a transaction truly went into the write buffer (not blocked by WPT, MPU or alignment checker).
Fixes issue #410 on cv32e40s.
=> Fix for issue #410 on cv32e40s

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_align_check.sv, rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/cv32e40x_if_stage.sv, rtl/cv32e40x_prefetch_unit.sv, rtl/cv32e40x_prefetcher.sv, sva/cv32e40x_alignment_buffer_sva.sv, sva/cv32e40x_core_sva.sv, sva/cv32e40x_if_stage_sva.sv, sva/cv32e40x_mpu_sva.sv
Detecting misaligned pointers in the IF stage. Propagating alignment status down the pipeline and flagging exception code 0x0 if not ok.
Added assertions for checking that only mret pointers can cause misaligned instruction address exceptions. Added assertions to check that the alignment buffer only signal one valid for each pointer (currently failing), and that the alignment buffer must signal instr_valid_o if is not currently prefetching and the controller wants us to prefetch (currently failing).
The new and failing assertions will be addressed in a coming PR
=> Misaligned pointer update.

bhv/cv32e40x_rvfi.sv, bhv/include/cv32e40x_rvfi_pkg.sv
Signaling rvfi_valid + rvfi_trap.cliptr for faulted CLIC pointer fetches.
Fixes issue #414 on cv32e40s.
=> Fix for issue #414 on cv32e40s.

rtl/cv32e40x_controller_fsm.sv
"// todo: Halting ID and killing it later will not work for Zce (push/pop)".
This is taken care of by the flag id_stage_haltable, which makes sure the ID stage cannot be halted when a seuqence (or clic pointer) is in progress as seen from the ID stage.
=> Removed todo from controller_fsm.

rtl/cv32e40x_controller_fsm.sv
The same todo exists on cv32e40s.  Note that the todo on e40s is still valid, and when merging this removal to e40s the fix must also be performed.
=> Removed e40s-specific todo from controller_fsm.

rtl/include/cv32e40x_pkg.sv
This commit fixes a minor issue with the width of a literal that triggered a warning with the sv2v converter.
=> Fix literal width

rtl/cv32e40x_controller_fsm.sv
- Refactored code for ctrl_fsm_o.halt_id in the controller_fsm
- Updated comments and description for halt_id.
SEC clean.
=> Fix for issue #675.

sva/cv32e40x_controller_fsm_sva.sv
Added assertions to check that no synchronous events can be missed during any non-FUNCTIONAL FSM state.
=> Fix for issue #666.

rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_csr.sv, rtl/include/cv32e40x_pkg.sv
- Changes CSR implementation to be identical to the unhardened version on cv32e40s
- Introduces MASK and RESET_VAL for all CSRs
- Use a function to compute next value for all next-value assignments
This should align X and S better, and allow for unimplemented bits in CSRs to be either 0 or 1.
Once this PR is approved, similar changes will be done for the remaining CSRs.
SEC clean.
=> Partial fix for issue #766

rtl/cv32e40x_wb_stage.sv
=> Removed two TODO's related to wb_valid.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, sva/cv32e40x_rvfi_sva.sv
Added assertions for the specific issue, and updated assertions to accomodate the change.
=> Fixed issue where rvfi_trap.debug would not be set for an etrigger.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv
Fix 3 issues:
1. Transfers could be missed if there's backpressure from WB when lsu_data_trans_valid is asserted.
2. If the 2nd half of a split misaligned transfer is blocked, it would still be reported on rvfi_mem.
3. rvfi_mem_rdata was not correct for split misaligned transfers. Only rdata from 1st transfer would be reported on rvfi_mem
The bugs fixed in this PR were found by assertions written for https://github.com/openhwgroup/cv32e40x/issues/648
The PR for these assertions will follow.
=> Update rvfi_mem interface.

rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/include/cv32e40x_pkg.sv
=> Signal rename

yaml/csr.yaml.m4
Description:
Jvt setting has changed, and is now the following:
This PR updates the yaml file accordingly. 
This PR is related to another PR in the verif repo: https://github.com/openhwgroup/core-v-verif/pull/1894
(This PR is "moved" from the cv32e40s repo. See: https://github.com/openhwgroup/cv32e40s/pull/453)
=> Update jvt settings csr.yaml.m4

rtl/cv32e40x_debug_triggers.sv
Each tdata1 instance now has a separate _n value. This is needed for the upcoming debug spec change where multiple instances of tdata1 may be written at once upon debug entry (hit1, hit0).
SEC clean (tested with 0, 1 and 4 triggers enabled)
=> Refactored tdata1_n logic 

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/integration.rst
mintthresh.th is now always 8 bits wide
=> Removed parameter CLIC_INTTHRESHBITS from the user manual.

rtl/cv32e40x_clic_int_controller.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv
Renamed mintthres_o to mintthresh_th_o in cs_registers.
=> Dret to lower privilege mode no longer clears mintthresh.

rtl/cv32e40x_alignment_buffer.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ff_one.sv, rtl/cv32e40x_load_store_unit.sv, rtl/cv32e40x_mpu.sv, rtl/cv32e40x_sequencer.sv, rtl/cv32e40x_wb_stage.sv
=> Lint cleanup

rtl/cv32e40x_cs_registers.sv
The pointer address returned by accessing mnxti would be wrong if CLIC_ID_BITS was less than 4. Fix was to pad the interrupt ID used by mnxti with zeroes to reach the desired alignment.
=> Fix for issue #884.

rtl/cv32e40x_cs_registers.sv
Rewrote fix for issue #884 as the original fix did not pass lint in a different tool than what was originally used.
=> Lint fix for issue #884

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, sva/cv32e40x_rvfi_sva.sv
Correct minor mistakes in cv32e40x..
1) correct bind to use an existing signal
2) add debug_mode when setting the debug_cause signal. ebreak will be repported in rfvi_dbg in debug mode, but is not a prioritized debug cause in case there are several reasons to enter debug mode.
=> Corrections

sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_cs_registers_sva.sv
Add TODO for assertion: a_no_wfi_wakeup_on_wfe
Make sure CLIC is enabled when checking a_minhv_unique. If CLIC is disabled make sure a_minhv_unique's antecedent never occurs
=> a_minhv_unique require clic, add todo for a_no_wfi_wakeup_on_wfe:

rtl/cv32e40x_controller_fsm.sv
Added comments to explain timing of 'pending_single_step' and it's valid use cases.
=> Removed two todos in controller_fsm.

rtl/cv32e40x_clic_int_controller.sv, sva/cv32e40x_clic_int_controller_sva.sv, sva/cv32e40x_core_sva.sv
Added assertion to check that an interrupt request must be raised the cycle after waking up for an interrupt if interrupts are globally enabled.
=> Removed todo in clic_int_controller.

rtl/cv32e40x_ex_stage.sv
Renaming of signals and addition of valid-signals to get more consistent coding.
Removed TODO about performing COCO analysis.
SEC clean.
=> Removed todo's in EX stage.

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_mpu.sv, sva/cv32e40x_mpu_sva.sv
Added assertion to prove that the second half of a split misaligned will not reach the MPU if the first part is blocked by the MPU.
=> Removed todo in MPU

bhv/cv32e40x_rvfi.sv
Changed from:
(ebreak_in_wb_i && debug_mode_q_i) ? DBG_CAUSE_EBREAK : ctrl_fsm_i.debug_cause
to:
ctrl_fsm_i.debug_cause
in both lines in question. Checked with a temporary assertion to check for correctness.
=> Fix for issue #892

docs/user_manual/source/exceptions_interrupts.rst
Added information about priority of CLIC interupts vs NMIs in the "Exceptions and Interrupts" chapter in the user manual.
=> Fix for issue #881

rtl/cv32e40x_div.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_mult.sv, sva/cv32e40x_mult_sva.sv
Factored halt_ex/kill_ex out of mul_en and div_en - multiplier and divider now handles them theirselves.
In the divider, div_en_i and valid_i was then duplicates, changed to using only valid_i.
SEC clean (with multiplier operation converted to add to enable converging SEC)
=> Fixed todo's related to mul_en/div_en i EX stage

rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_bypass.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_ex_stage.sv, rtl/cv32e40x_id_stage.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
Conservatively stalling ID for any implicit CSR read while any implicit or explicit CSR write is in EX or WB (unchanged)
Conservatively stalling EX for any implicit CSR read while any implicit or explicit CSR write is in WB
Conservatively stalling EX for any explicit CSR rad while any implicit CSR write is in WB
Precisely stalling EX for any explicit CSR read while an explicit CSR write to the same CSR is in WB.
=> Optimized CSR stalls

bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, sva/cv32e40x_controller_fsm_sva.sv
a_valid_jump cannot assert that we don't jump when ID is halted, so it was decided to add an assertion verifying that the register used for JALR is stable until JALR retires.
=> Fix todo in assertion a_valid_jump.

rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv, sva/cv32e40x_cs_registers_sva.sv
mcause.minhv only set when taking an exception for a CLIC pointer or mret pointer restart. When jumping due to an mret, mcause.minhv is checked regardless of mcause.mpp.
=> Updates for CLIC spec (august 23)

rtl/cv32e40x_controller_fsm.sv, sva/cv32e40x_controller_fsm_sva.sv
Removed reference to old debug spec. Wording from spec is still valid as of September 2023. Added assertions related to halting and killing wb, sleep mode and debug.
Removed 'debug_mode_q' from list of reasons to wake from sleep. (SEC clean)
=> Controller_fsm cleanup and asserts

yaml/csr.yaml.m4
This PR fixes a few problems with the CSR Yaml.
Relates to https://github.com/openhwgroup/cv32e40x-dv/pull/37 and https://github.com/openhwgroup/core-v-verif/pull/2186.
=> Update CSR Yaml

docs/user_manual/source/rvfi.rst
Added signals rvfi_mem_atop, rvfi_mem_err, rvfi_mem_exokay and rvfi_mem_memtype to the RVFI chapter of the user manual.
=> Added missing signals to rvfi_mem documentation.

rtl/cv32e40x_cs_registers.sv, rtl/cv32e40x_id_stage.sv
Parameterized Zicntr only registers.
Parameterized speculative reads for Xif.
LEC clean with ZICNTR=1'b1 and X_EXT=1'b1.
Logically equivalent to cv32e40s with all core exclusive features disabled (ZICNTR=1'b0, X_EXT=1'b0, etc.).
=> Parameterize Zicntr and Xif features

rtl/cv32e40x_controller_fsm.sv
In PR #498 on cv32e40s there was a list of required changes to the e40x controller to get to a SEC clean state.
This PR addresses two changes to align the two cores. The first bullet below is just a refactor and is SEC clean. 
The second is not SEC clean, and the reasoning here is that without this change the e40x can kill the pipeline for debug or interrupts before a CSR flush handshake is completed (before the jump to the instruction after the CSR is performed).
- Refactored branch_in_ex / branch_taken ex. SEC clean.
- Not allowing async debug, interrupts or NMI when csr_flush_ack_q == 1. NOT SEC clean.
=> Fixes after running SEC vs cv32e40s with SECURE=0.

docs/user_manual/source/control_status_registers.rst
Updated description of mtvec reset and initialization.
Other CSR reset values seems clear to me, those with dependencies on various parameters or input values are described.
=> Fix for issue #586

yaml/csr.yaml.m4
This PR updates `csr.yaml.m4`.
`mcause.MPP` had U-mode as reset value, on the X.
A `warl_legalize` produced wrong generated test code on a WRLR field.
Special CLIC access behavior also generated wrong test code.
=> CSR Yaml Updates

bhv/cv32e40x_rvfi.sv, rtl/cv32e40x_controller.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_core.sv, rtl/cv32e40x_load_store_unit.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_controller_fsm_sva.sv
=> Introduced type for lsu_err_wb

rtl/cv32e40x_align_check.sv, rtl/cv32e40x_ff_one.sv, rtl/cv32e40x_id_stage.sv
- xif_offloading_o in id_stage was not driven when X_EXT==0
- core_resp_o.wpt_match was not driven in the align checker in the LSU
- MSB of sel_nodes within ff_one was not driven. Also fixed on cv32e40p with commit ab162975a52b79e2f2bd5dc7511a9e849485c22d.
=> Fixed undriven signals

rtl/cv32e40x_sequencer.sv, sva/cv32e40x_sequencer_sva.sv
Updated sequencer to only udate flops when needed, old code always updated flops causing a always-on clock gate.
SEC clean.
=> Sequencer clock gate optimization

docs/user_manual/source/pma.rst
Described how PMA errors may affect instructions which perform multiple memory operations.
=> Fix for issue #61

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, bhv/include/cv32e40x_rvfi_pkg.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_debug_triggers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_rvfi_sva.sv
Misaligned atomics will now issue codes 5 and 7 if they otherwise pass the MMU. The rvfi_trap.cause_type field will be set to 3 to mark that codes 5 and 7 are for misaligned atomics.
=> Removed exception codes 4 and 6 for misaligned atomics.

bhv/cv32e40x_rvfi.sv, bhv/cv32e40x_wrapper.sv, rtl/cv32e40x_controller_fsm.sv, rtl/cv32e40x_cs_registers.sv, rtl/include/cv32e40x_pkg.sv, sva/cv32e40x_clic_int_controller_sva.sv
Mret with mcause.minhv==1 will now perform CSR side effects of the mret once the instruction itself reaches WB. The following table lookup will complete the instruction, and update CSRs if the table lookup failed during fetch.
Updates to RVFI to enable signaling correct CSR rdata/rmask and wdata/wmask for the combined CSR effetcts of an mret with a following table lookup.
SEC clean when mcause.minhv is assumed to be 0.
=> Bugfix for mret with mcause.minhv==1

rtl/cv32e40x_sequencer.sv
Both cm.mva01s and cm.mvsa01 flagged illegal instruction if rs1 == rs2.
With this fix cm.mva01s allows rs1 == rs2, and the core will not flag illegal instruction.
=> BUGFIX: for cm.mva01s when rs1 == rs2

bhv/cv32e40x_rvfi_sim_trace.sv, bhv/include/cv32e40x_rvfi_pkg.sv
Update string casting in cv32e40x_rvfi_sim_trace for better simulator compatibility.
Moving trace_t typedef to package to enable reuse outside of cv32e40x_rvfi_sim_trace
=> Tracer update

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/rvfi.rst
This PR adds ` (CSR)` and ` (RVFI)` to the corresponding section headers in the user manual.
The reason is that I several times have wanted to look up those things, hit `ctrl+f` and found nothing, having to stop for a moment and try to remember what we titled our section headers or scan through the list of sections until I find it.
This change will alleviate some discontentment.
I have not tested this in any way.
For those familiar with the formatting, you might visually recognize if it is correct or not.
=> User Manual Abbreviations - `CSR` and `RVFI` in Section Names
